### ISSUE TITLE
toast 组件 show 和 hide 方法间隔很短 会显示一个没有内容的toast 条

### ISSUE THREAD

**Issue by lf75152798** [salt-ui/saltui#100]
## 这是一个

错误报告

## SaltUI 版本

//g.alicdn.com/platform/tingle-ui/3.1.5/salt-ui.min.js

## 浏览器、操作系统等环境信息

iphone 6splus 手机

## 复现步骤
当一个 
Toast.show({
          type: 'loading',
          content: '提交中...',
          autoHide: false
        });
接着执行
Toast.hide()
![image](https://user-images.githubusercontent.com/33650737/34976485-d2f44bbe-fad1-11e7-8a1f-a28c31feb564.png)

**Comment by eternalsky** [comment]
这个问题已经修复了，请更新到最新版本

**Comment by lf75152798** [comment]
//g.alicdn.com/platform/tingle-ui/3.1.5/salt-ui.min.js   我现在的版本，最新的是多少

**Comment by eternalsky** [comment]
请查看 changelog
