### ISSUE TITLE
两个 SelectField 级联选择 会有问题

### ISSUE THREAD

**Issue by lf75152798** [salt-ui/saltui#102]
> 请按照以下模板填写

## 这是一个

- [x] 错误报告

## SaltUI 版本

//g.alicdn.com/platform/tingle-ui/3.1.5/salt-ui.min.js

## 浏览器、操作系统等环境信息

手机或者电脑上 都会出现

## 复现步骤

两个 SelectField 级联选择，单二级 SelectField 选择完成后，再选择一级的 SelectField ， 由于级联，二级SelectField 选项值变了，但是 再次打开二级SelectField，不做任何操作，点击确定。获取到的值还是第一次选择的二级SelectField 的值 。

**Comment by eternalsky** [comment]
请使用最新版本，再来看下是否还有问题。https://codepen.io/eternalsky/pen/WpzYrv

**Comment by lf75152798** [comment]
https://codepen.io/anon/pen/aqbeKE 问题还是存在的。

**Comment by eternalsky** [comment]
demo 里也不是最新的，我换成了最新的版本，https://codepen.io/eternalsky/pen/ZrYEXd，看下是否还有问题

**Comment by lf75152798** [comment]
ok   验证已修复
