### ISSUE TITLE
请saltui支持react 16以上版本

### ISSUE THREAD

**Issue by 5123095** [salt-ui/saltui#103]
> 请按照以下模板填写

## 这是一个

- [] 错误报告
- [x ] 功能需求

## SaltUI 版本
^3.5.1
## 浏览器、操作系统等环境信息
浏览器

**Comment by LiangZugeng** [comment]
最近我们在总体升级自己的技术框架，我们也想把React升级到16，SaltUI适配到React 16有时间计划吗？难度大不大啊？

**Comment by eternalsky** [comment]
4.x 已经全面支持 react16
