### ISSUE TITLE
NumberPicker，加减号不起作用

### ISSUE THREAD

**Issue by smilexlong** [salt-ui/saltui#107]
## 这是一个

- [x] 错误报告
- [ ] 功能需求

## SaltUI 版本
3.5.14

## 浏览器、操作系统等环境信息
google, win7 

## 复现步骤
使用NumberPicker，加减号不起作用，官网上的demo也是一样
https://salt-ui.github.io/components/number-picker

**Comment by eternalsky** [comment]
因为组件里默认使用 touch 模式，所以在 PC 的预览环境里无效，手机上访问是 ok 的，demo 我们做下适配。
