### ISSUE TITLE
Toast 的层级优先级比Dialog和Popup的优先级低

### ISSUE THREAD

**Issue by smilexlong** [salt-ui/saltui#111]
## 这是一个

- [x] 错误报告
- [ ] 功能需求

## SaltUI 版本
3.5.17
## 浏览器、操作系统等环境信息
Google，win7

## 复现步骤
先打开Dialog或者Popup，再弹出Toast，轻提示会被遮住，而不是显示在最上面

**Comment by eternalsky** [comment]
3.5.16 里我们刚修复了这个问题，你确定你现在使用的是最新版吗~

**Comment by eternalsky** [comment]
请提供 demo：https://codepen.io/eternalsky/pen/WpzYrv

**Comment by smilexlong** [comment]
https://codepen.io/smilexlong/pen/EQjjzG 这个是Dialog  ，还是被遮住的
