### ISSUE TITLE
DateTime,SelectField 控件无法通过其他方式触发弹出层隐藏

### ISSUE THREAD

**Issue by smilexlong** [salt-ui/saltui#112]
## 这是一个

- [x] 错误报告
- [ ] 功能需求

## SaltUI 版本
3.5.17

## 浏览器、操作系统等环境信息
Google，win7

## 复现步骤
在移动端点击返回按钮时，希望能通过方法调用将打开的日期选择框，或者下拉选择框弹出层隐藏。不然跳到下一个页面弹出层还存在。

Datetime 控件可以通过 
 <Datetime
          {...this.datetimeProps}
          slotRef={s => t.slot1 = s}
          title="日期选择"
          value={t.state.value1}
          columns={Datetime.YMD}
          onConfirm={(value) => { this.onConfirm(value, 'value1'); }}
          onCancel={() => { this.onCancel('value1'); }}
        />
this.slot1 .show() 来展现日期选择弹出层。  调用this.slot1.hide() 无法隐藏。 

SelectField  目前没看到有方法提供来实现主动触发隐藏弹出框

**Comment by eternalsky** [comment]
Field 目前还没有考虑做直接唤起，如果有类似需求，可以用非 Field 类型的组件，比如 slot、dateTime 等做拼接。

**Comment by smilexlong** [comment]
dateTime 有触发展现的，但是没有可以主动调用触发隐藏的。SelectField 是都没有  像这类有弹出层的是不是有应该有方法暴露出来方便展示盒隐藏

**Comment by eternalsky** [comment]
@smilexlong SelectField 是带表单域部分的，弹出层是 slot。

**Comment by eternalsky** [comment]
datetime 可以提供对应的隐藏方法。

**Comment by smilexlong** [comment]
datetime 的隐藏方法什么时候可以更新。  对于 SelectField表单控件，弹出层是 slot的这类控件。可以通过获取s组件中的slot来控制show和hide

**Comment by eternalsky** [comment]
dateTime 也可以靠 slotRef 来 hide 的，请查看一下自己的使用方法，如果还有问题，请提交一下 demo，我们再分析。

**Comment by smilexlong** [comment]
![image](https://user-images.githubusercontent.com/19772709/35654773-91b148fa-0729-11e8-85bd-1f8eac217f9a.png)   在组件中通过点击按钮执行showSlot方法可以展示dateTime 展出层，在该方法中使用延时执行关闭方法是可以隐藏弹出层的。  但是在卸载组件时调用 this.slot1.hide(); 就没有作用或者报没有hide方法
