### ISSUE TITLE
ScrollList的问题 ScrollList的Item使用Group.List会一直触发ScrollList的onload

### ISSUE THREAD

**Issue by feitiana03120** [salt-ui/saltui#116]
[js.docx](https://github.com/salt-ui/saltui/files/1689324/js.docx)
> 请按照以下模板填写

# 这是一个

- [x] 错误报告

## 复现步骤

* ScrollList同样设置了高度，同样的数据。当ScrollList的Item元素 用ScrollList.Item 没问题，用Group.List会出现一直触发onload；
# codepen地址
https://codepen.io/feitiana03120/pen/NyNOoQ

**Comment by eternalsky** [comment]
看了你的 demo，onLoad 并不是一直在触发，只有拉到页底的时候才出发，不清楚你说的一直在触发是指什么

**Comment by feitiana03120** [comment]
GroupList和ScrollList.Item我都写在Demo里了。使用GroupList会有问题，codepen里我把GroupList注释掉了。现在我已经切换到有问题的了，再帮忙看一下
![3](https://user-images.githubusercontent.com/14845860/35787288-edef5864-0a67-11e8-8527-0111af8cee95.png)

**Comment by feitiana03120** [comment]
@eternalsky

**Comment by eternalsky** [comment]
定义组件的方式不好造成的，https://codepen.io/eternalsky/pen/bLpZMp?editors=0010，稍微修改一下就没这个问题了。

**Comment by feitiana03120** [comment]
@eternalsky 我需要升级saltui吗

**Comment by feitiana03120** [comment]
@eternalsky 能请教下，为什么把function GroupList放到class外面就可以了吗？
