### ISSUE TITLE
PhotoField暴露onImagePreview事件提供更大的灵活性

### ISSUE THREAD

**Issue by LiangZugeng** [salt-ui/saltui#124]
## 这是一个

- [ ] 错误报告
- [x] 功能需求

## SaltUI 版本
3.6.0

## 背景和问题
我们正在使用PhotoField进行图片上传及预览，为了优化使用带宽，目前我们的想法是上传图片后后台生成小图（长边600px）和略缩图（长边150px），在PhotoField中默认显示略缩图（考虑到用户不一定会要查看图片，这样做可以节省网络带宽和减少加载时间），当用户点击PhotoField中的图片进行预览时让用户看小图（还是减少加载时间和节省带宽），然后还想在预览界面提供“查看原图”按钮，点击此按钮加载上传的原图。目前PhotoField使用了ImageViewer而且没有暴露onImagePreview事件，而是内部调用了自己的handlePreview函数，所以我们的想法不能实现。

## 需求
PhotoField暴露onImagePreview事件出来，如果控件使用者挂接了此事件，则使用调用者的处理函数，否则使用目前的handlePreview函数，给调用者更大的灵活性。

## 代码改动
1. 在PhotoField.propTypes中加入onImagePreview属性，类型PropTypes.func
2. 在PhotoField.defaultProps中设置onImagePreview属性的默认值为undefined
3. 在[render函数](https://github.com/salt-ui/saltui/blob/fbe79308dd4787eb6af8c5e4f640289f6bc6284f/src/PhotoField/PhotoField.jsx#L200)中修改onImagePreview，改为
```
onImagePreview: (index) => { this.props.onImagePreview === undefined ? this.handlePreview(index) : this.props.onImagePreview(index); },
```

**Comment by eternalsky** [comment]
思路是可以的，要注意有钉钉版和 H5版都要有这个功能。
