### ISSUE TITLE
selectFiled 下拉选择不能默认选择第一行，必须滑动才能选择！

### ISSUE THREAD

**Issue by TCjinzhi** [salt-ui/saltui#129]
## 这是一个
- [x] 错误报告
## 复现步骤
第一步:从后台加载数据放入到selectfield的options属性
第二步：下拉选择直接确定，选中不了第一行

**Comment by eternalsky** [comment]
3.3.6 不是最新版本，https://github.com/salt-ui/saltui/blob/master/CHANGELOG.md

**Comment by eternalsky** [comment]
升级到最新版本后如果还有类似问题 reopen，请附带 codePen demo。
