### ISSUE TITLE
可否支持批量操作组件

### ISSUE THREAD

**Issue by koupeng** [salt-ui/saltui#131]
> 请按照以下模板填写

## 这是一个

- [ ] 错误报告
- [x] 功能需求

## 复现步骤
![1](https://user-images.githubusercontent.com/6110684/37071562-0268e088-21f8-11e8-9a3c-a1ff5c6aab2a.png)

**Comment by eternalsky** [comment]
这是一个页面功能，组件库不会支持到这么大颗粒度的业务话组件。

**Comment by koupeng** [comment]
好的，谢谢。
