### ISSUE TITLE
CalendarField `onOk` 回调被调用时参数不一致

### ISSUE THREAD

**Issue by tommytroylin** [salt-ui/saltui#132]
## 这是一个

- [x] 错误报告

## SaltUI 版本 
3.6.4

## 浏览器、操作系统等环境信息
macOS Sierra
chrome 64

## 复现步骤

* [CodePen 链接](https://codepen.io/anon/pen/yvmxLx)

直接执行代码
1. 点击打开日期选择浮层。什么都不做。点击确认
控制台输出 `props.value` 的值
2. 点击打开日期选择浮层。选择其他日期。点击确认
控制台输出 `{ value: newValue }`

## workaround
配置 props.value 时，只传入 `{ value: (new Date()).valueOf() }` 类型的值。

**Comment by eternalsky** [comment]
恩，是的，推荐 workaround 里的用法。后续 Demo 里也改一下，提出的现象 1 也会统一到 2 上去。
