### ISSUE TITLE
PhotoField组件最大上传BUG

### ISSUE THREAD

**Issue by MForL** [salt-ui/saltui#133]
## 这是一个

- [x] 错误报告
- [ ] 功能需求

## SaltUI 版本
最新版
## 浏览器、操作系统等环境信息
chrome

## 复现步骤
PhotoField组件，当允许多张上传的时候，最大上传限制无效(maxUpload)。
说明：
       `<PhotoField max={5} maxUpload={9} />`
       如果一张一张上传，9张上传最大限制生效。
       如果已经上传8张，下次上传进行多选上传，将全部都可以上传，这样就超出9张了

**Comment by fengsx** [comment]
同样的，如果最多上传九个文件。8个成功了，1个失败了。这个时候，失败的1个，会显示重新上传。但是此时还可以上传第十个文件。如果第十个文件上传成功。失败的那个点击重新上传，还是会上传上去的。这样就绕过最大个数限制了。

**Comment by eternalsky** [comment]
我试了一下，虽然是可以选择多个，单个只会上传最终不超过 9 个的图片

**Comment by eternalsky** [comment]
@fengsx 反馈的问题是有效的。

**Comment by eternalsky** [comment]
新版本和交互讨论之后，上传中和上传失败都会算入计数，解决这一问题。
