### ISSUE TITLE
PhotoField 和 ImageViewer 在图片预览时的问题

### ISSUE THREAD

**Issue by fengsx** [salt-ui/saltui#137]
> 请按照以下模板填写

## 这是一个

- [x] 错误报告
- [ ] 功能需求

## SaltUI 版本
3.5.21
## 复现步骤
单页应用中，在 PhotoField中 预览图片的时候，如果操作前进和后退，页面内容已经变了，但是图片预览状态不会消失

* 你可以在这里提交你的 [CodePen 链接](https://codepen.io/eternalsky/pen/WpzYrv) 以及描述复现的步骤

**Comment by eternalsky** [comment]
ImageViewer 的 API 调用方式导致，需要业务上监听页面变化时去手动调用 remove，详见更新的 doc。PhotoField 可以在内部做一下调用。
