### ISSUE TITLE
ScrollList安卓端下拉时抖动，手势问题，时而抖的很厉害

### ISSUE THREAD

**Issue by Fniy** [salt-ui/saltui#139]
> 请按照以下模板填写

## 这是一个ScrollList的Bug

- [x] 错误报告 下拉抖动
- [x] 功能需求
无论下拉或上拉，页面不要抖动。

## SaltUI 版本
3.7.1

## 浏览器、操作系统等环境信息
钉钉安卓端，魅族MX6等

## 复现步骤
https://salt-ui.github.io/components/scroll-list
打开以上链接，钉钉扫码体验，安卓端抖动，ios端未测
* 你可以在这里提交你的 [CodePen 链接](https://codepen.io/eternalsky/pen/WpzYrv) 以及描述复现的步骤
<img width="785" alt="qq20180319-215641 2x" src="https://user-images.githubusercontent.com/5724828/37599889-ce965a10-2bc0-11e8-9da3-dd92836e361c.png">

**Comment by eternalsky** [comment]
请再详细描述你的复现过程，以及你所描述的抖动具体是指那种情况，最好有 gif 或者录屏可以参考。

**Comment by eternalsky** [comment]
没有回应超过 7 天
