### ISSUE TITLE
[datetime]年月日组件，设置disabledDate后，默认确定的返回值错误

### ISSUE THREAD

**Issue by leedut** [salt-ui/saltui#143]
> 请按照以下模板填写

## 复现方式

当设置disabledDate后，直接点击“确定按钮”，返回值不是当前的默认选中值，而是当天0点。

## 截图说明
如下图，设置了时间范围为3月26号~，而点击确定的回调时间确是3月24号0点（当天的时间）。
![image](https://user-images.githubusercontent.com/10243337/37865679-fc897760-2fba-11e8-9f3a-adcd7e527963.png)

- [x] 错误报告
- [ ] 功能需求

## 复现步骤

* 你可以在这里提交你的 [CodePen 链接](https://codepen.io/eternalsky/pen/WpzYrv) 以及描述复现的步骤

**Comment by eternalsky** [comment]
能否提供你的组件的详细配置，方便我们复现？或者提供 codePen 链接。
