### ISSUE TITLE
DataTimeField设置minDate和maxDate报错

### ISSUE THREAD

**Issue by orangeyyy** [salt-ui/saltui#147]
> 请按照以下模板填写

## 这是一个

- [x] 错误报告
- [ ] 功能需求

## SaltUI 版本
3.7.5
## 浏览器、操作系统等环境信息
chrome、mac

## 复现步骤
1，当当前值不在minDate和maxDate之间时，会报错，如下图所示：这种场景是存在的，比如一个时间选择器只能选择5天以后的日期，我5天前选择今天，是ok的，但是我今天要更改表单的时候，minDate就变成的5天以后，但是form表单的值是今天，然后就报错了。
![image](https://user-images.githubusercontent.com/19667299/37908971-3bfaa734-313c-11e8-8c24-779ec831bb0e.png)
2，当当前值在minDate和maxDate之间时，月份的可选项不准确，选择后面的月份会报错，如下图所示:例子中本来我只能选3月-4月的日期，结果显示可以选到后面的月份，但是选择会报错
![image](https://user-images.githubusercontent.com/19667299/37909235-f424314a-313c-11e8-933c-8266d786632a.png)

* 你可以在这里提交你的 [CodePen 链接](https://codepen.io/eternalsky/pen/WpzYrv) 以及描述复现的步骤

**Comment by orangeyyy** [comment]
https://codepen.io/orangexxx/pen/qoVrrR

**Comment by eternalsky** [comment]
目前你所有使用的版本，3.7.5 非最新版本， 3.7.6 正是修复了这一问题，请关注 changelog 的变化，如果还有问题，请 reopen 并说明最新版本的情况。
