### ISSUE TITLE
PickerView选择面板无法滑动

### ISSUE THREAD

**Issue by xiaxinyu8535** [salt-ui/saltui#160]
> 请按照以下模板填写

## 这是一个

- [x] 错误报告
- [ ] 功能需求

## SaltUI 版本
3.8.2
## 浏览器、操作系统等环境信息
安卓手机浏览器（com.android.browser ）以及钉钉内查看

## 复现步骤
代码使用dva（基于redux的前端框架）+react.js编写，在使用PickerView组件时，选择面板中的内容无法向下滑动并且控制台报警如下
![qq 20180408115210](https://user-images.githubusercontent.com/29685493/38463085-63b1f6c8-3b24-11e8-9af7-8de5324f581f.png)

* 你可以在这里提交你的 [CodePen 链接](https://codepen.io/eternalsky/pen/WpzYrv) 以及描述复现的步骤

**Comment by eternalsky** [comment]
已修复
