### ISSUE TITLE
ios中PickerField的搜索界面布局问题

### ISSUE THREAD

**Issue by xiaxinyu8535** [salt-ui/saltui#163]
> 请按照以下模板填写

## 这是一个

- [x] 错误报告
- [ ] 功能需求

## SaltUI 版本
3.8.7
## 浏览器、操作系统等环境信息
ios版浏览器

## 复现步骤
点击pickerField组件，弹出搜索界面，点击搜索框使光标聚焦且弹出手机键盘，此时整个页面自动放大（搜索框右边的取消键已经被挡住，需要拖动手机屏幕到右方才能看到），下方搜索结果也被挡住了左侧界面，需要向左拖动才能查看。任意选择一条数据关闭搜索界面，之前的界面也放大了
猜测是ios的模拟键盘影响了布局，安卓浏览器中没有这个问题，使用chrome中的iphone模拟器点击搜索时不会弹出模拟键盘，也没有这个问题
![img_1805](https://user-images.githubusercontent.com/29685493/38655419-1741ca68-3e47-11e8-9d0b-567d7c549c85.PNG)

![img_1806](https://user-images.githubusercontent.com/29685493/38655424-1df3e828-3e47-11e8-85f9-86415a45f38a.PNG)

* 你可以在这里提交你的 [CodePen 链接](https://codepen.io/eternalsky/pen/WpzYrv) 以及描述复现的步骤

**Comment by eternalsky** [comment]
页面的 HTML 信息提供一下，怀疑你可能不是使用的我们提供的架手架，meta 信息不全或者不低。

**Comment by xiaxinyu8535** [comment]
十分感谢！将nowa提供的脚手架内的meta添加到项目中解决了
