### ISSUE TITLE
Nav-Bar 在 iOS 下 fixed 状态会存在被输入框顶上去的问题

### ISSUE THREAD

**Issue by SurfaceW** [salt-ui/saltui#164]
Nav-Bar 在 iOS 的钉钉容器下 fixed 状态会存在被 iOS输入键盘区域 顶上去的问题。

版本：最新

1. Nav-Bar 嵌套其它 div 容器里面
2. 当有类似遮罩蒙层上，Trigger 了 Input 之后会弹出 iOS 的输入键盘，输入键盘会将 NavBar 上顶
3. 一旦取消蒙层，Nav-Bar 会突然定位回去，造成闪动

**Comment by eternalsky** [comment]
fixed 定位在钉钉容器中的刷新问题，使用 absolute 定位解决。
