### ISSUE TITLE
scroll-list组件在下拉刷新的时候很容易就造成点击触发事件

### ISSUE THREAD

**Issue by z810276431** [salt-ui/saltui#17]
如题，稍微用力就会触发点击事件而跳转

**Comment by eternalsky** [comment]
这个应该不是 scrollList 的问题，scrollList 本身没有点击触发跳转的逻辑，也不监听内部的点击事件，造成这个问题，应该考虑的是 每一个 Item 是不是给的点击跳转区域过大，对于高频操作是不是没有做好防抖处理。
