### ISSUE TITLE
昵称如果为“张三(123213123)”，结果头像只显示“3)”这种，很不友好，建议把数字和()过滤掉

### ISSUE THREAD

**Issue by fuxun2008** [salt-ui/saltui#171]
> 请按照以下模板填写

## 这是一个

- [x] 错误报告
- [ ] 功能需求

## 复现步骤

* 你可以在这里提交你的 [CodePen 链接](https://codepen.io/eternalsky/pen/WpzYrv) 以及描述复现的步骤

**Comment by eternalsky** [comment]
fix in https://github.com/salt-ui/saltui/pull/172
