### ISSUE TITLE
在Iphone 6sp 设备上,标题会消失

### ISSUE THREAD

**Issue by zhangshaoshuai1** [salt-ui/saltui#174]
> 请按照以下模板填写

## 这是一个

- [x] 错误报告

## 操作系统IPhone 6 sp 钉钉扫一扫

iphone 6 ,7 都不会出现问题
## 复现步骤
1.写入输入框的值
2.写入text值
3.确认后导航头消失
CodePen 
https://codepen.io/zhangshaoshuai1/pen/zjKOde?editors=1111
步骤:在Iphone 6sp 设备上,text于输入值后确定后标题头消失

**Comment by eternalsky** [comment]
本地用 iphone 7 没有复现出来，如果你那边有问题的话，建议可以将 navBar 的 position 改成 absolute 再试下。

**Comment by zhangshaoshuai1** [comment]
iphone 6 ,7 都不会出现问题
