### ISSUE TITLE
Popup组件与CascadeSelectField级联组件配合使用的异常关闭的问题

### ISSUE THREAD

**Issue by baifernlover** [salt-ui/saltui#177]
> 请按照以下模板填写

## 这是一个

- [x] 错误报告
- [ ] 功能需求

## SaltUI 版本
3.8.28
## 浏览器、操作系统等环境信息
 谷歌浏览器  苹果手机浏览器

## 复现步骤
1、在Popup组件弹出向下的菜单里，添加CascadeSelectField级联选择组件。
2、Popup.maskClosable 设置为false(点击蒙层不允许关闭）
3、单击CascadeSelectField组件，在弹出的菜单选择好内容后。单击确定后。CascadeSelectField组件关闭
Popup组件也关闭了 

* 你可以在这里提交你的 [CodePen 链接](https://codepen.io/eternalsky/pen/WpzYrv) 以及描述复现的步骤

**Comment by eternalsky** [comment]
非推荐使用方式。
