### ISSUE TITLE
Collapse组件右侧的 收起 展开箭显示异常

### ISSUE THREAD

**Issue by baifernlover** [salt-ui/saltui#179]
> 请按照以下模板填写

## 这是一个

- [x] 错误报告
- [ ] 功能需求

## SaltUI 版本
.8.28
## 浏览器、操作系统等环境信息
 谷歌浏览器  钉钉安卓浏览器

## 复现步骤

Collapse组件右侧的 收起 展开箭头无法正常显示  显示为一个小方块 
![image](https://user-images.githubusercontent.com/5907268/39559085-3c1e4cf0-4ec6-11e8-99b7-aaf5eaa23a1c.png)
 苹果手机上显示正常

**Comment by ShieldCN** [comment]
我的也是，请问有什么解决方法？

**Comment by baifernlover** [comment]
你把salt的版本更新一下再试试，貌似已经修复了

**Comment by eternalsky** [comment]
我猜你可能是在 nowa server 的开发环境下看到这个问题的，这是因为 默认配置里 css-loader 开启了 sourceMap，样式是以 dataURL 的形式插入进来的，因为 dataURL 不能下载任何资源，所以 iconfont 没有加载出来， 如果你是 build 出来的生产文件，应该不会有这个问题。
