### ISSUE TITLE
toast时间1500，用户反映一闪而过，时间太短，默认时间最好改成业界统一的3000

### ISSUE THREAD

**Issue by fuxun2008** [salt-ui/saltui#183]
> 请按照以下模板填写

## 这是一个优化点

- [x] 错误报告
- [ ] 功能需求

## SaltUI 版本
最新版本

## 浏览器、操作系统等环境信息
所有浏览器

## 复现步骤
移动端，toast默认

* 你可以在这里提交你的 [CodePen 链接](https://codepen.io/eternalsky/pen/WpzYrv) 以及描述复现的步骤

**Comment by eternalsky** [comment]
我们的设计里面，基础型带 icon 的是 1.5s，纯文字内容比较长的是 3s。后续会按照这个要求去修改。
