### ISSUE TITLE
H5版上传组件，钉钉下，限制为最多9张，图片上传能多余9张

### ISSUE THREAD

**Issue by xmissra** [salt-ui/saltui#186]
> 请按照以下模板填写

## 这是一个Bug

- [x] 错误报告
- [ ] 功能需求

## 浏览器、操作系统等环境信息
IOS和安卓的钉钉中

## 复现步骤
上传满9张后，删除部分张图片，然后继续再选择9张图片，然后就能上传多余9张图片了
* 你可以在这里提交你的 [CodePen 链接](https://codepen.io/eternalsky/pen/WpzYrv) 以及描述复现的步骤

**Comment by eternalsky** [comment]
能提供一下 codePen 的 demo 吗？我们本地看了一下是可以限制住 max 的。
