### ISSUE TITLE
H5版上传组件，第二次打不开选择附件的弹框

### ISSUE THREAD

**Issue by xmissra** [salt-ui/saltui#187]
> 请按照以下模板填写

## 这是一个问题

- [x] 错误报告
- [ ] 功能需求

## SaltUI 版本
3.8.31

## 浏览器、操作系统等环境信息
安卓版本的钉钉里面使用

## 复现步骤
H5版上传组件，点击上传，打开选择附件的弹框，这时点击空白处关闭弹框，再次选择”+“号打不开选择附件的弹框
* 你可以在这里提交你的 [CodePen 链接](https://codepen.io/eternalsky/pen/WpzYrv) 以及描述复现的步骤

**Comment by eternalsky** [comment]
这个看了一下，是钉钉容器的 bug，任何一个 `<input type="file" />` 都存在这个问题，正在联系钉钉解决。

**Comment by eternalsky** [comment]
钉钉的同学反馈，下一个版本中修复这个问题。

**Comment by eternalsky** [comment]
经确认，安卓 4.3.7 版本已经修复此问题。
