### ISSUE TITLE
H5版的图片上传组件取消选择图片后不能再次选择

### ISSUE THREAD

**Issue by yishengabcd** [salt-ui/saltui#188]
> 请按照以下模板填写

## 这是一个 
- [x] 错误报告

## SaltUI 版本
3.8.32

## 浏览器、操作系统等环境信息
小米MAX2 Anroid7.1.1 MIUI9.5 在钉钉微应用上使用
## 复现步骤
1､点击PhotoField.H5的相机图标，会弹出选择“上传文件”的弹窗，弹窗上有两个选项“照片和视频”和“手机文件”
2､此时点击空白的地方关掉弹窗；
3､然后再重新点击步骤1中的相机图标，则无法再次弹出“上传文件”的弹窗。
相关代码：
<PhotoField.H5
          label="上传图片"
          placeholder="请选择图片"
          max={4}
          maxUpload={9}
          name="file"
          url={rootPath+"/UploadFile"}
          photoList={this.state.photoList}
          onChange={this.onChange.bind(this)}
          onDelete={this.onDelete.bind(this)}
        />
* 你可以在这里提交你的 [CodePen 链接](https://codepen.io/eternalsky/pen/WpzYrv) 以及描述复现的步骤

**Comment by xmissra** [comment]
我也遇见这样的问题了

**Comment by yishengabcd** [comment]
是的，求解决啊。android版的有这个问题，pc版和ios版没出现此问题。

**Comment by eternalsky** [comment]
duplicate：https://github.com/salt-ui/saltui/issues/187，放到同一个 issue 当中。
