### ISSUE TITLE
源码npm install 不成功，node版本8.5.0 npm版本5.5.1

### ISSUE THREAD

**Issue by dagang17** [salt-ui/saltui#19]
pm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated express@2.5.11: express 2.x series is deprecated
npm WARN deprecated connect@1.9.2: connect 1.x series is deprecated
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm ERR! code E404
**npm ERR! 404 Not Found: @ali/gitlab-apis@^2.1.0**

npm ERR! A complete log of this run can be found in:

**Comment by eternalsky** [comment]
404 ？ 感觉这是 npm 的问题，换成其他版本再试一下。

**Comment by jklin1978** [comment]
"devDependencies": {
    "@ali/gitlab-apis": "^2.1.0",

感觉是这个问题？

**Comment by jklin1978** [comment]
ali/gitlab-apis

**Comment by eternalsky** [comment]
更新了一下，现在应该是可以的了。

**Comment by jklin1978** [comment]
还是一样的错误，
npm ERR! code E404
npm ERR! 404 Not Found:  @@ali/gitlab-apis@^2.1.0

**Comment by jklin1978** [comment]
提示没找到：ali/gitlab-apis@^2.1.0

**Comment by eternalsky** [comment]
再试一下~

**Comment by jklin1978** [comment]
npm install成功了，
> saltui@3.1.7 start C:\Develop\Temp\saltui
> gulp server

module.js:471
    throw err;
    ^
Error: Cannot find module '@ali/gitlab-apis'

**Comment by jklin1978** [comment]
npm start后还是出现Error: Cannot find module 'ali/gitlab-apis'

**Comment by eternalsky** [comment]
移除掉了批处理用的代码，再试一下吧。

**Comment by jklin1978** [comment]
总算可以啊，多谢！：）
