### ISSUE TITLE
下拉刷新与上拉加载冲突

### ISSUE THREAD

**Issue by bubblepp1** [salt-ui/saltui#191]
## 这是一个

- [x] 错误报告

## SaltUI 版本
beta

## 浏览器、操作系统等环境信息
chrome windows

## 复现步骤

需要在一个页面实现使用下拉刷新页面 以及上拉动态加载数据功能时 由于上拉加载要求设置position: absolute; 所以下拉没反应 无法刷新页面

**Comment by eternalsky** [comment]
上拉加载应该没有要求非要设置 position: absolute;。

**Comment by eternalsky** [comment]
我们的 demo 就是下拉和上拉在一起的，https://salt-ui.github.io/components/scroll-list
