### ISSUE TITLE
scrollList升级到最新的3.8.32版本后出现问题

### ISSUE THREAD

**Issue by z810276431** [salt-ui/saltui#192]
saltui依赖，老版本是没有问题的，更新到最新的版本，scrollList初始加载没问题，在下拉刷新成功后就出现图片这样的字样
![_15260108801795](https://user-images.githubusercontent.com/16434735/39906241-0a6377d6-5514-11e8-8e92-0b6a774f8614.png)

**Comment by eternalsky** [comment]
去大致定位一下，不过因为你没有提供复现的 demo 链接，所以如果我本地不好复现的话，那么可能解决的时间可能会比较长。

**Comment by eternalsky** [comment]
本地复现不了你的情况，下拉加载都是正常的。

**Comment by z810276431** [comment]
https://codepen.io/z810276431/pen/gzdNOd这是codepen地址，麻烦查看一下，谢了

**Comment by eternalsky** [comment]
最新版已修复，请查看 CHANGELOG
