### ISSUE TITLE
Tab控件activeKey属性不能接受数字类型的参数

### ISSUE THREAD

**Issue by LiangZugeng** [salt-ui/saltui#193]
## 这是一个

- [x] 错误报告
- [ ] 功能需求

## SaltUI 版本
3.8.33

## 浏览器、操作系统等环境信息
Windows 10 (Version 10.0.16299.431)
Chrome (Version 66.0.3359.139 (Official Build) (64-bit))
SaltUI (Version 3.8.33)

## 问题
Tab控件activeKey属性不能接受数字类型的参数，但在SaltUI的文档中activeKey的值类型为String或者Number。
![image](https://user-images.githubusercontent.com/20870130/39982031-978d09c4-5785-11e8-8360-322bb333a03b.png)

## 复现步骤
1. 打开链接的pen，pen中的代码将Tab.activeKey设置为0，期望能选中第一个Tab.Item，实际的效果是没有任何Tab.Item被选中。（此步骤已经能重现问题）
2. 在pen中将state中的activeTabIndex改为："0"，并保存，这时候第一个Tab.Item被选中。（此步骤用于验证activeKey属性只能处理string类型的值）

CodePen链接：https://codepen.io/LiangZugeng/pen/OZEoWj

**Comment by eternalsky** [comment]
是的，这里是正能接受字符串，文档要修改一下。
