### ISSUE TITLE
不使用Nowa使用SaltUI 报错

### ISSUE THREAD

**Issue by 1602228514** [salt-ui/saltui#194]
错误报告

## 浏览器、操作系统等环境信息
谷歌浏览器 66.0.3359.139 WIN 10 VSCode Node.js

## 复现步骤
使用 create-react-app demo 安装 react
使用 yarn eject 释放配置
安装 react-router，react-router-dom，refast，fastclick，saltui，react-loadable
创建文件 control/SnTabBar/index.js
     使用官方tabBar源码
创建文件 pages/form/index.js 
    使用官方上传图片源码
 App.js 使用路由默认打开form

点击tabBar，点击图片删除按钮，均报错。Uncaught TypeError: Cannot assign to read only property 'WebkitTransform' of object '#<Object>'

**Comment by eternalsky** [comment]
目前 SaltUI 仅适配到 15.x，近期会做 16.x 的适配，所以你可以先用 15.x 来试下，nowa 生成的脚手架里也是用的 15.x

**Comment by 1602228514** [comment]
感谢。尽快适配16.x
