### ISSUE TITLE
SelectField的问题

### ISSUE THREAD

**Issue by 5123095** [salt-ui/saltui#197]
> 请按照以下模板填写

## 这是一个

- [x] 错误报告
- [ ] 功能需求

## SaltUI 版本
^3.8.37
## 浏览器、操作系统等环境信息
钉钉

## 复现步骤
SelectField在选择时，页面会scroll到最上面，是否是控件的问题?

**Comment by eternalsky** [comment]
saltui 的版本能否给一个确切的版本，有可能是最近您没有升级导致的。你可以在控制台里 `npm list --depth=0 | grep saltui` 看下确切的版本。

**Comment by 5123095** [comment]
是saltui@3.8.37
