### ISSUE TITLE
CitySelectField 增加一个必须选到最后一个叶子节点才可以点击确定的Props

### ISSUE THREAD

**Issue by fengsx** [salt-ui/saltui#198]
> 请按照以下模板填写

## 这是一个

- [ ] 错误报告
- [x] 功能需求

## SaltUI 版本
3.8.39
## 复现步骤
![image](https://user-images.githubusercontent.com/7709602/40660800-ac4553d4-6384-11e8-8142-66ddd95482a9.png)

* 你可以在这里提交你的 [CodePen 链接](https://codepen.io/eternalsky/pen/WpzYrv) 以及描述复现的步骤

**Comment by eternalsky** [comment]
这个是之前 eslint 留下的一个 bug，修复后，目前是必须选中到叶子节点。
