### ISSUE TITLE
ScrollList 下拉刷新完头部不隐藏

### ISSUE THREAD

**Issue by mateng04** [salt-ui/saltui#199]
> 请按照以下模板填写

## 这是一个

- [x] 错误报告
- [ ] 功能需求

## SaltUI 版本
^3.8.39

## 浏览器、操作系统等环境信息
钉钉

## 复现步骤
进入加载数据，然后上拉加载两次数据，然后下拉刷新数据，刷完以后头部不隐藏

https://codepen.io/anon/pen/rKaOOB

**Comment by eternalsky** [comment]
提供的 demo 无法运行起来，请先将 demo 调通。
