### ISSUE TITLE
不支持Typescript吗？

### ISSUE THREAD

**Issue by xuguogang** [salt-ui/saltui#20]
我没有找到声明文件呢，是否支持Typescript呢？

**Comment by eternalsky** [comment]
暂时还没有支持 ts 的计划。

**Comment by LiangZugeng** [comment]
不开新的issue了，借这个issue问吧，距上次回答已经大半年了，对支持ts有计划了吗？或者是已经有计划提供.d.ts文件了？

**Comment by xiaoyao-web** [comment]
是的，随着ts的用户数量逐渐增多，是否考虑支持ts？
