### ISSUE TITLE
Popup

### ISSUE THREAD

**Issue by YoungJoeyzy** [salt-ui/saltui#202]
> 请按照以下模板填写

## 这是一个

- [x] 错误报告

## SaltUI 版本
3.8.41

## 浏览器、操作系统等环境信息
钉钉

## 复现步骤

原有的popup框，无论是用.show方法控制出现还是通过visible属性控制出现，当第二个popup框.show之后，原本的popup框都会被‘挤走’关闭，无法共存

**Comment by eternalsky** [comment]
duplicate:  https://github.com/salt-ui/saltui/issues/201 请在同一个 issue 中编辑提交。
