### ISSUE TITLE
Popup无法同时弹出两个

### ISSUE THREAD

**Issue by Astroinist** [salt-ui/saltui#203]
> 请按照以下模板填写

## 这是一个

- [x] 错误报告
- [ ] 功能需求

## SaltUI 版本
3.8.40
## 浏览器、操作系统等环境信息
钉钉客户端，以及chrome均可重现

## 复现步骤
使用popup.show先弹出第一个层，在这个层中在使用popup.show弹出第二个层，此时第一个层会被关闭。
同样的现象在 popup.show的弹出层中使用 CalendarField，在calendar弹出时也会使popup被关闭

* 你可以在这里提交你的 [CodePen 链接](https://codepen.io/astroinist/pen/QxEdyN) 以及描述复现的步骤

**Comment by eternalsky** [comment]
我们其实是不推荐同时弹出两个 Popup 的，如果有类似情况，建议将第一个 Popup，做新页面处理，多层 Popup 容易引发用户误操作和带来一系列的问题。

**Comment by Astroinist** [comment]
列表上的过滤很容易出现2次弹层的场景，比如过滤中有用到按照时间区间（CalendarField）条件，或者选择内部组织机构（自定义选择组件）等都可能会用到2次弹层。毕竟列表上的过滤不能做到一个新页面上去让用户进行数据筛选，这样体验就太差了。

**Comment by eternalsky** [comment]
如果想要分成多实例的话，就使用标签形式 <Popup /> ，Popup.show 会使用统一个共享实例。

**Comment by Astroinist** [comment]
使用标签形式的popup，如果内部内容过多，在钉钉客户端内打开时，无法向下滚动。即在钉钉客户端内运行，pupup标签形式 滚动条失效。（注：钉钉客户端内运行才有此现象，pc浏览器中会报警告但可以滚动）
