### ISSUE TITLE
EmployeeField组件在去掉tip的情况下，接收人和图片之间有较大的空白

### ISSUE THREAD

**Issue by baifernlover** [salt-ui/saltui#207]
> 请按照以下模板填写

## 这是一个

- [x] 错误报告
- [ ] 功能需求

## 复现步骤
EmployeeField组件在去掉tip的情况下，接收人和图片之间有较大的空白
![image](https://user-images.githubusercontent.com/5907268/41220422-f12157dc-6d93-11e8-877d-fd7147f17ada.png)

代码如下
<EmployeeField
         label="接收人"
          placeholder="请选择"
          corpId="dingf8f7ada678fc911635c2f4657eb6378f"
          startWithDepartmentId ={0}
          value={[{
            label: '欧阳震华',
            key: '023456',
            avatar: 'https://gw.alicdn.com/tfs/TB1D9YIkb9YBuNjy0FgXXcxcXXa-200-200.jpg',
          },{
            label: '欧阳震华',
            key: '023456',
            avatar: 'https://gw.alicdn.com/tfs/TB1D9YIkb9YBuNjy0FgXXcxcXXa-200-200.jpg',
          }]}
          onChange={(value) => { this.onChange(value); }}> 
</EmployeeField>

**Comment by eternalsky** [comment]
可以看下最新版（3.9.11）还有这个问题吗？如果还有的话，请提交一个复现 codePen demo 给我们。
