### ISSUE TITLE
关于增加PhotoField和EmployeeField 组件的onclick方法自定义的建议

### ISSUE THREAD

**Issue by baifernlover** [salt-ui/saltui#217]
## 这是一个功能建议

建议增加组件的onclick方法自定义功能，比如PhotoField 组件的onclick方法，当前的情况是直接调用系统的上传接口。某些场景里需要直接调用手机本地相机的功能，比如某些场合只能现场拍照的要求等。antd-mobileUI库的ImagePicker组件就可以实现自定义click方法的功能。**

附上ImagePicker组件的链接如下 ：https://mobile.ant.design/components/image-picker-cn/

另外EmployeeField的组件也有类似的自定义方法的需求

* 你可以在这里提交你的 [CodePen 链接](https://codepen.io/eternalsky/pen/WpzYrv) 以及描述复现的步骤

**Comment by eternalsky** [comment]
标题改一下，哪个组件。另，不是一定是调用系统的上传接口，H5 版本可以自己选择上传接口。

**Comment by baifernlover** [comment]
PhotoField.H5组件可以自己定义上传接口？比如点击时调用手机的相机？

**Comment by eternalsky** [comment]
调用手机的相机和定义上传接口是两件事，h5 不能指定使用相册还是相机，但是呼起 filePicker，上传 url 支持自定义配置。

**Comment by baifernlover** [comment]
懂了。我的想法是能否实现自定义呼起的功能，比如可以选择 呼起 filePicker也调用自定义的方法，比如直接调用相机
