### ISSUE TITLE
PickerField 在 iPhone X 兼容性处理上的 bug

### ISSUE THREAD

**Issue by fengsx** [salt-ui/saltui#221]
> 请按照以下模板填写

## 这是一个

- [x] 错误报告
- [ ] 功能需求

## SaltUI 版本
3.9.6
## 复现步骤
PickerField 在移动端上的在 iPhone X 兼容性处理上的 bug。iPhone X 是好的，普通的出问题了
![image](https://user-images.githubusercontent.com/7709602/41700390-ad0daaae-755a-11e8-8ed8-9a81cb172aad.png)

* 你可以在这里提交你的 [CodePen 链接](https://codepen.io/eternalsky/pen/WpzYrv) 以及描述复现的步骤

**Comment by eternalsky** [comment]
fixed in 3.9.9
