### ISSUE TITLE
Avatar组件不支持显示纯数字字符串，比如name=“11”

### ISSUE THREAD

**Issue by huxiany** [salt-ui/saltui#223]
Avatar组件不能正常显示包含数字的字符串，比如name=“11”或 name=“t11”，现象如下：

现象1：当传入的是纯数字字符串时，Avatar中显示空白；
现象2：当name=“t11”时，Avatar中显示t，而不是t1。

 [CodePen 链接](https://codepen.io/huxiany/pen/PaBmrG?editors=0010)

**Comment by eternalsky** [comment]
我们之前做个一个优化，过滤了数字和括号这些我们认为不适合展示在 Avatar 里的字符，集中展示汉字和字母这些有意义的场景，你们的场景是什么样的？

**Comment by huxiany** [comment]
我们的场景是：在Avatar中显示商品的编号或关键信息，编号通常是两位数的，部分关键信息也会包含数字。

**Comment by eternalsky** [comment]
这个感觉在 avatar 里显示感觉不是很合适，我们之前过滤掉数字，就是因为 Avatar 里只能显示两个字符，如果都是 11 21 这种的起不到多大的指示性。

**Comment by huxiany** [comment]
是这样的，我们在Avatar中显示的字符并不是重复的11或21，而是不重复的数字，比如1，2，3 ......99（通常不会大于100），其作用类似于Id，是可以标识这一条信息的，具有指示性作用，所以可否取消过滤掉数字的限制，Avatar就默认显示两个字符，具体显示的内容由调用者自行定义，这样的话通用性会不会好一些呢？

**Comment by eternalsky** [comment]
考虑开放自定义 filter，如果自定义了 filter，则不走默认的 filter

**Comment by huxiany** [comment]
那请问开放自定义filter的版本什么时候发布呢？主要是我们升级saltUI后，我们的系统界面显示异常，如下图：

![default](https://user-images.githubusercontent.com/28701403/42141383-6472f7c0-7ddb-11e8-8dde-bb5ba4b38d26.png)

**Comment by eternalsky** [comment]
ok，今天一会发布一个版本支持一下吧。

**Comment by eternalsky** [comment]
应该可以。

**Comment by eternalsky** [comment]
最新版支持了，see https://github.com/salt-ui/saltui/blob/master/docs/Avatar.md#filter

**Comment by huxiany** [comment]
温馨提示：你刚发布的那个版本的CHANGELOG.md中的日期写错了，写成了2018-07-13，今天是2018-07-03，
https://github.com/salt-ui/saltui/blob/master/CHANGELOG.md
