### ISSUE TITLE
TabBar的items属性问题

### ISSUE THREAD

**Issue by z810276431** [salt-ui/saltui#224]
问一下TabBar的items属性中子菜单选项的title设了没有作用，不显示title
![1530010612 1](https://user-images.githubusercontent.com/16434735/41907211-c1b48a10-7972-11e8-9c8e-313e334fd9d3.jpg)

**Comment by eternalsky** [comment]
这个看了下，确实是这样设计的，我们希望在中间出现的 icon，可以直接表意，不需要对应的问题。

**Comment by z810276431** [comment]
嗯，主要是一个图标icon不加文字，除了常用的添加，删除按钮，其他的确实不好去识别

**Comment by eternalsky** [comment]
底部 Tab 中间区域就是一些最常用的重功能：如添加、拍照等，如需要显示标题，可以直接用 5 个统一Tab，全部 icon+文字

**Comment by z810276431** [comment]
我现在的应用场景是中间新增按钮，点击之后弹出多个按钮，多种类型的新建，这样的话光用图标是没有办法直观的判断是哪一种新增

**Comment by eternalsky** [comment]
这种全部放到下部 TabBar 感觉也不是特别合适，建议做成一个入口，然后在入口对应的话面，再展示多种新建。

**Comment by z810276431** [comment]
本来写的一个单独页面，客户不要，就要如此炫酷，无奈

**Comment by eternalsky** [comment]
我们的交互设计上没有考虑这里支持标题，或者考虑把文字做到 icon 当中。

**Comment by z810276431** [comment]
好的，谢谢
