### ISSUE TITLE
PhotoField的显示样式问题

### ISSUE THREAD

**Issue by LiangZugeng** [salt-ui/saltui#225]
> 请按照以下模板填写

## 这是一个

- [x] 错误报告
- [ ] 功能需求

## SaltUI 版本
v3.9.3

## 浏览器、操作系统等环境信息
MacOS 10.13.5 + Google Chrome 67.0.3396.87

## 复现步骤

1. [3.8.2版本的SaltUI，PhotoField显示高度和其他控件一致](https://codepen.io/LiangZugeng/pen/WygMGb)

2. [3.9.10版本的SaltUI，PhotoField显示高度比其他控件要矮11个像素](https://codepen.io/LiangZugeng/pen/xrYPwr)

**Comment by eternalsky** [comment]
fix in 3.9.11
