### ISSUE TITLE
自定义table行的BUG

### ISSUE THREAD

**Issue by xuexiaoao** [salt-ui/saltui#228]
## 这是一个

- [x] 错误报告
- [ ] 功能需求

## SaltUI 版本
3.7.7
## 浏览器、操作系统等环境信息
任意安卓浏览器

## 复现步骤

```javascript
columns:[
        { dataKey: 'date',  title: '账期', align: 'center',width:0.2},
        { dataKey: 'fee',  title: '收入', align: 'center',width:0.3,
            render:function(cellData, rowData){
                return renderTableRow(cellData,rowData,rowData.perAndMonth.feePer,rowData.perAndMonth.feeLastPer);
            }
        }
    ],

function renderTableRow(cellData, rowData,per,lastPer) {
return <div onClick={(e)=>{

        Dialog.alert({
            title: '对比详情',
      
            content: '测试',
            onConfirm(e) {
              console.log(e);
            },
          });

    }}>
        {cellData}<span style={{fontSize:18,color:iconColor,marginLeft:'1'}}>{iconType}</span>
    </div>;
}
```

### 在安卓手机上有时触发点击事件后，Dialog会显示后自动消失，在IOS上没有出现这个问题

**Comment by eternalsky** [comment]
请给出 codePen demo，https://codepen.io/eternalsky/pen/WpzYrv

**Comment by xuexiaoao** [comment]
demo在这，https://codepen.io/xuexiaoao/pen/OEqdoO
点击出账收入字段，会发现Dialog.alert弹出两次

**Comment by xuexiaoao** [comment]
demo在这，https://codepen.io/xuexiaoao/pen/OEqdoO
在安卓手机上，点击出账收入的字段，Dialog有时会弹出后自动消失，我在手机上选择了右下角的1x，其他选项没有复现这个问题

**Comment by eternalsky** [comment]
请明确稳定复现条件

**Comment by xuexiaoao** [comment]
在安卓浏览器，点击出账收入列的任意字段，会发现Dialog弹出后自动消失
![incomes](https://user-images.githubusercontent.com/18185523/42252306-914b479a-7f6e-11e8-8bd4-71235b7a2dad.gif)

**Comment by eternalsky** [comment]
本地也试了下，不能稳定复现，猜测是类似双击的行为

**Comment by xuexiaoao** [comment]
onTouchStart替换了click事件解决了这个问题
