### ISSUE TITLE
关于DatetimeField组件的问题

### ISSUE THREAD

**Issue by huxiany** [salt-ui/saltui#229]
## 浏览器、操作系统等环境信息
chrome

## 问题描述

*在Chrome中测试我们的系统功能发现，使用了DatetimeField组件的界面，在输入其它组件（比如TextField）的value时，界面反应非常慢（备注：这个现象用codePen复现不了，在我们的系统中是一直存在的），经调试发现在更新其它组件的value，render刷新时会多次进入到DatetimeField组件，查看了DatetimeField的源代码，componentWillReceiveProps()函数中没有比较slotValue的值是否有变化，直接setState()，这里的处理方式是否是导致上述现象的原因，请帮忙看一下，谢谢！
```
  componentWillReceiveProps(nextProps) {
    this.setState({

      slotValue: Datetime.getSlotFormattedValue(nextProps.value, nextProps),

     });
  }
```

**Comment by eternalsky** [comment]
released
