### ISSUE TITLE
CheckboxField组件选择数据后，在props.data未发生变更时，无法正常显示选中的值

### ISSUE THREAD

**Issue by air-eienniutau** [salt-ui/saltui#231]
> 请按照以下模板填写

## 这是一个

- [x] 错误报告
- [ ] 功能需求

## SaltUI 版本
~3.10.0

## 浏览器、操作系统等环境信息
chrome可复现

## 复现步骤
~3.10.0版本会下出现CheckboxField组件slot mode下选择数据后组件无展示的bug。
fix issue #230 的修改中将 this.state.selectedText = selectedText; 修改为了 return selectedText;
但在 组件的handleConfirm中未将接受到的值setState
https://github.com/salt-ui/saltui/blob/master/src/CheckboxField/CheckboxField.jsx#L123

当前demo中的CheckboxFieldDemo不会出现上述问题是因为demo中正好将onchange接受到的data再次作为props.data传递给组件，此时componentWillRecieveProps中修改了state.selectedText
而下述demo则会出现此bug
https://codepen.io/air_wataru/pen/BVgqBX

* 你可以在这里提交你的 [CodePen 链接](https://codepen.io/eternalsky/pen/WpzYrv) 以及描述复现的步骤

**Comment by eternalsky** [comment]
fixed in https://github.com/salt-ui/saltui/commit/6205277a2d1ec13351c6bb26ed62db5a9f3fca93
