### ISSUE TITLE
NumberPicker点击加减会不停的跳转问题（经常出现，需要耐心点几次）

### ISSUE THREAD

**Issue by liuwf0314** [salt-ui/saltui#232]
> 请按照以下模板填写

## 这是一个BUG

- [x] 错误报告
- [ ] 功能需求

## 浏览器、操作系统等环境信息
浏览器显示是好的，只有手机有问题

## 复现步骤
安卓手机vivo X7测出来的，点击减号，数字会一直跳到最小；点击加号，数字会一直跳到最大
* https://codepen.io/anon/pen/KeOavo

**Comment by eternalsky** [comment]
请完善 title

**Comment by eternalsky** [comment]
其他手机是否有类似问题？

**Comment by liuwf0314** [comment]
会出现，

**Comment by liuwf0314** [comment]
会出现，安卓和苹果测试了都会出现
