### ISSUE TITLE
数字输入框NumberField 支持调用数字键盘

### ISSUE THREAD

**Issue by sunzhenglove** [salt-ui/saltui#238]
## 这是一个

- [ ] 错误报告
- [x] 功能需求

## 浏览器、操作系统等环境信息
ios钉钉内置环境开发，非浏览器

## 复现步骤

* 希望可以支持参数定义来支持是否调用数字键盘，这样输入手机号、金额、数量就会很方便用户。

**Comment by LiangZugeng** [comment]
我们之前也在研究如何可以调用iOS的数字键盘，如果是浏览器应用，iOS是没有办法指定纯数字键盘的。 @sunzhenglove 你说非浏览器是什么意思？SaltUI只能运行在浏览器环境，不能用于Native app啊。
