### ISSUE TITLE
希望saltui对根元素的字体大小的设定支持自定义配置

### ISSUE THREAD

**Issue by wisetc** [salt-ui/saltui#239]
> 请按照以下模板填写

## 这是一个

- [ ] 错误报告
- [x] 功能需求

## SaltUI 版本

3.10.5

## 浏览器、操作系统等环境信息

Mac OS X high Sierra

## 复现步骤

将saltui集成到已有的应用中的时候，当引用saltui的组件，会生成一个style的标签用来重置html的font-size，这个操作导致了原来的媒体查询的规则对html `font-sze`的设置被覆盖掉，希望saltui设置rem的时候，可以给一个配置，让使用者自定义根元素`font-size`的大小。如下图

![saltui](https://user-images.githubusercontent.com/9448115/42986629-d5b0b7b4-8c28-11e8-86d3-d9a6ae8a29a6.png)

我现在的解决方案是这样的，

![reset rem](https://user-images.githubusercontent.com/9448115/42986664-0624de02-8c29-11e8-9b16-d0c85d610931.png)

但是我感觉不太好，希望saltui组件可以自带这样的功能。

[codepen](https://codepen.io/wisetc/pen/vayavL)

**Comment by eternalsky** [comment]
能介绍下你现在使用 root fontsize 的场景吗？因为大部分场景下，你可以使用 body 层级的 font-size

**Comment by wisetc** [comment]
我主要用来做iphone5和iphone6的适配，我以iphone6为基准，将其`font-size`设置为`100px`

**Comment by eternalsky** [comment]
也就是说你自己做了一套 REM 系统，不想用 Saltui 提供的？建议最好和组件公用一套 REM，否则一些组件的样式可能会有问题。
