### ISSUE TITLE
组件Table在ios上数值为空的时候，会出现显示问题

### ISSUE THREAD

**Issue by liuwf0314** [salt-ui/saltui#240]
> 请按照以下模板填写

## 这是一个BUG

- [x] 错误报告
- [ ] 功能需求

## 复现步骤

组件Table在ios上数值为空的时候，只有在ios上table显示有问题，安卓没问题

* 你可以在这里提交你的 [CodePen 链接](https://codepen.io/eternalsky/pen/WpzYrv) 以及描述复现的步骤

**Comment by eternalsky** [comment]
请提供复现 demo
