### ISSUE TITLE
模态对话框Layer，配置maskCloseable，关闭之后，有对应的回调函数吗，因为maskCloseable并不能改变visible的值

### ISSUE THREAD

**Issue by raohuangxing** [salt-ui/saltui#242]
> 请按照以下模板填写

## 这是一个功能需求

- [ ] 错误报告
- [x] 功能需求

## SaltUI 版本
	ver. 3.8.13
## 复现步骤

* 你可以在这里提交你的 [CodePen 链接](https://codepen.io/eternalsky/pen/WpzYrv) 以及描述复现的步骤

**Comment by raohuangxing** [comment]
callback

**Comment by eternalsky** [comment]
推荐使用 Popup 组件
