### ISSUE TITLE
PhotoField组件不支持自定义的上传方法

### ISSUE THREAD

**Issue by wisetc** [salt-ui/saltui#246]
> 请按照以下模板填写

## 这是一个

- [x] 错误报告
- [x] 功能需求

## SaltUI 版本

latest

## 浏览器、操作系统等环境信息

钉钉

## 请求功能

请问saltui PhotoField组件怎么使用自定义的上传方法，要把图片上传至oss支不支持？

当拦截组件自带的上传功能时，使用oss的sdk上传，图片缩略图上会显示重新上传。

**Comment by wisetc** [comment]
PhotoField组件不支持返回的结果是xml的情况。

![image](https://user-images.githubusercontent.com/9448115/43674417-621ed81e-9806-11e8-9be1-5478040bb7de.png)

当用的是第三方的服务，如阿里云的oss的时候，返回的数据格式很可能是xml，如下图，就会报错，而且不工作。

![image](https://user-images.githubusercontent.com/9448115/43674437-905fe5a6-9806-11e8-9ae2-547de649f8d6.png)

**Comment by wisetc** [comment]
PhotoField组件上传图片至oss，采用了两种方法都不理想。

第一种方法，采用组件附带formdata的方法，结果oss返回的上传结果只能为空或者xml，引起组件报错，无法显示正确的上传结果。

![image](https://user-images.githubusercontent.com/9448115/43677815-fb2a7070-983a-11e8-8bb3-bc4c1052675e.png)

第二种方法，采用oss的sdk自定义上传至oss，能够得到预期的结果，利用正确的返回结果添加进photoList，可以显示上传成功后的图片，但是会引起photoList和列队中的图片（未通过组件上传不显示的部分）同时存在，导致显示的最大图片数最多是实际设置的最大图片数的一半，如下图

![image](https://user-images.githubusercontent.com/9448115/43677900-4cd51622-983c-11e8-83ac-05b3ea419c6a.png)

**Comment by wisetc** [comment]
@eternalsky 谢谢你的回复，主要是oss的没有返回内容只有返回成功状态导致组件报错，我们没有oss后端，采用前端直传，图片数据可以上传成功，但是会显示不了成功的状态，问题还是没有解决，看起来通过后端返回签名应该有会不一样的结果。
![oss doc](https://user-images.githubusercontent.com/9448115/44184296-422d2080-a141-11e8-96b4-06aa415727cf.png)

![组件出错](https://user-images.githubusercontent.com/9448115/44184325-5d982b80-a141-11e8-9284-0de1df479a31.png)

**Comment by wisetc** [comment]
@eternalsky 要利用`onfileuploadcompleting`钩子去改造一下`response.rawResponse.rawResponse`，但是不知道值应该怎么设置

**Comment by eternalsky** [comment]
@wisetc response 可以 set，这些钩子里的方法，可以在 uploadcore 的文档里查询，文档很多，所以是以链接的形式呈现的。

<img width="665" alt="2018-08-16 2 44 46" src="https://user-images.githubusercontent.com/8038928/44192715-1884f100-a163-11e8-86b3-dddf83d235ba.png">
