### ISSUE TITLE
Datatime 组件滑动特别卡

### ISSUE THREAD

**Issue by jianghang1995** [salt-ui/saltui#257]
> 请按照以下模板填写

## 这是一个

- [x] 错误报告
- [ ] 功能需求

## SaltUI 版本
  3.10.7

## 复现步骤

* 你可以在这里提交你的 [CodePen 链接](https://codepen.io/eternalsky/pen/WpzYrv) 以及描述复现的步骤

**Comment by eternalsky** [comment]
3.10.7 刚针对这个做了一个优化，能否详细说明下，钉钉的版本以及使用卡的安卓机型？

**Comment by jianghang1995** [comment]
苹果6，小米，三星s8,oppo R11  这几种直接那官方的demo测试都会卡 钉钉版本都是最新的

**Comment by eternalsky** [comment]
官方的 demo 指的是哪个 demo，能给一个你们那边卡的 demo 吗？

**Comment by jianghang1995** [comment]
https://salt-ui.github.io/components/datetime  就是这个demo

**Comment by jianghang1995** [comment]
我直接吧这个copy下来用钉钉微应用打开来就特别卡，但是通过钉钉扫码出来就很正常

**Comment by eternalsky** [comment]
@jianghang1995 这里有三个 demo，用的是哪个？

**Comment by jianghang1995** [comment]
columns属性为Datetime.YMDWHM时

**Comment by eternalsky** [comment]
默认的时间是从 1900 - 2051，会生成 1000+ 的选项，如果你的业务里不需要这么多时间，可以设置 minDate 和 maxDate 来收束范围，减少生成的选项，这样卡顿就会得到缓解。
