### ISSUE TITLE
标签页Tab组件的内容区域在很多安卓手机上不能滑动！！！！

### ISSUE THREAD

**Issue by liuwf0314** [salt-ui/saltui#266]
> 请按照以下模板填写

## 这是一个BUG

- [x] 错误报告
- [ ] 功能需求

## SaltUI 版本 
     4.0.1

## 浏览器、操作系统等环境信息
      安卓机：OPPOR11s，华为荣耀9（型号：STF-AL00）测出问题；
      苹果手机显示正常

## 复现步骤
     标签页Tab组件内容区域内容很多时，滑动屏幕，但是滑动不了

* [CodePen 链接](https://codepen.io/liuwf0314/pen/BOzWZK)

**Comment by eternalsky** [comment]
如何滑动？上下滑动还是左右滑动？

**Comment by liuwf0314** [comment]
上下滑动

**Comment by liuwf0314** [comment]
上下滑动tab内容，

**Comment by eternalsky** [comment]
4.0.2 修复，试一下？

**Comment by liuwf0314** [comment]
试了，还是不行

**Comment by eternalsky** [comment]
确定更新到 4.0.2 了吗，上面修改里的内容生效了吗？https://github.com/salt-ui/saltui/commit/4ae70964aede35fda5abdaac2e4f63bb79ad17b5

**Comment by eternalsky** [comment]
自己不要去修改 saltui 的 src，没有用处。
