### ISSUE TITLE
tab组件最新版本不能用

### ISSUE THREAD

**Issue by raohuangxing** [salt-ui/saltui#269]
> 请按照以下模板填写

## 这是一个

- [x] 错误报告
- [ ] 功能需求

## SaltUI 版本
SaltUI 4.0.6
## 复现步骤

* 你可以在这里提交你的 [CodePen 链接](https://codepen.io/eternalsky/pen/WpzYrv) 以及描述复现的步骤

**Comment by raohuangxing** [comment]
请技术人员尽快修复

**Comment by eternalsky** [comment]
能具体说明下是怎么不能用吗？

**Comment by eternalsky** [comment]
请提供一下具体的错误描述，截图

**Comment by raohuangxing** [comment]
官网上面的，tab组件打开之后，变成了竖排的，之前版本是横排
![qq 20180903110942](https://user-images.githubusercontent.com/38023804/44965748-ec8eab80-af69-11e8-8b02-dbd59f98bf1d.png)

**Comment by raohuangxing** [comment]
应该不要另外设置样式吧，

**Comment by eternalsky** [comment]
站点上的资源引用除了一些问题，正常组件使用应该是没问题的，下午会修复站点。

**Comment by raohuangxing** [comment]
我退回以前的版本^3.8.39，是可以用的，最新版本会变成竖排
![qq 20180903115510](https://user-images.githubusercontent.com/38023804/44966940-b0127e00-af70-11e8-8803-d2e5cab860f6.png)

**Comment by eternalsky** [comment]
可以试下最新发布的 4.0.8 的版本

**Comment by raohuangxing** [comment]
4.0.8也可以了，非常感谢！

**Comment by raohuangxing** [comment]
可以把官网上的也同步一下吗

**Comment by eternalsky** [comment]
站点 CDN 有些问题，我们稍后会进行修复。
