### ISSUE TITLE
折叠Collapse组件 箭头图标丢失

### ISSUE THREAD

**Issue by Zyyao11** [salt-ui/saltui#270]
> 请按照以下模板填写

## 这是一个

- [x] 错误报告
- [ ] 功能需求

## SaltUI 版本
4.0.8
## 浏览器、操作系统等环境信息
谷歌浏览器 Mac os

## 复现步骤
![image](https://user-images.githubusercontent.com/33918562/45289809-aa90d700-b520-11e8-8555-8d1d6f60b373.png)

* 你可以在这里提交你的 [CodePen 链接](https://codepen.io/eternalsky/pen/WpzYrv) 以及描述复现的步骤

**Comment by eternalsky** [comment]
duplicate: https://github.com/salt-ui/saltui/issues/179
