### ISSUE TITLE
Dialog关闭问题

### ISSUE THREAD

**Issue by z810276431** [salt-ui/saltui#275]
有个问题，关于Dialog的，如果Dialog弹出后直接点击返回，那么Dialog不关闭，我加了监听事件来监听返回事件，手动调用hide方法，但是如果没有点击过dialog，那么我返回就直接报错了，有没有方法可以判断页面是否有Dialog弹出层
版本是目前最新的，4.0.10

**Comment by eternalsky** [comment]
下次提 issue，请按照模板来，如果issue不规范，我们会降低处理的优先级，谢谢配合。你提到的问题，我们先看一下。

**Comment by eternalsky** [comment]
fix in 4.0.11
