### ISSUE TITLE
android上刷不出页面

### ISSUE THREAD

**Issue by qq578023708** [salt-ui/saltui#281]
> 请按照以下模板填写，不按照标准模板填写的 issue 将降低处理优先级。

## 这是一个

- [x] 错误报告
- [ ] 功能需求

## 浏览器、操作系统等环境信息

Mozilla/5.0 (Linux; U; Android 8.0.0; zh-cn; BND-AL10 Build/HONORBND-AL10) AppleWebKit/537.36 (KHTML, like Gecko) MQQBrowser/7.3 Chrome/37.0.0.0 Mobile Safari/537.36
## 复现步骤
使用NOWA创建的脚手架，直接在安卓手机上使用自带浏览器预览，整个页面是空白，使用其他浏览器则无问题。
* 你可以在这里提交你的 [CodePen 链接](https://codepen.io/eternalsky/pen/WpzYrv) 以及描述复现的步骤

**Comment by eternalsky** [comment]
兼容性问题，自己 debug 调试一下。估计是换掉 Object.assign 就可以了。
