### ISSUE TITLE
CalendarField 渲染性能优化

### ISSUE THREAD

**Issue by zhangbenber** [salt-ui/saltui#283]
> 请按照以下模板填写，不按照标准模板填写的 issue 将降低处理优先级。

## 这是一个

- [x] 功能需求

## SaltUI 版本
4.1.2

![image](https://user-images.githubusercontent.com/7821581/45799322-9f3b6980-bcdf-11e8-90a5-981ffe4598a9.png)

**Comment by eternalsky** [comment]
需要复现demo
