### ISSUE TITLE
在用Tab的时候,下面如果做了滚动条,在安卓机型上面向上拖动无反应

### ISSUE THREAD

**Issue by zhangshaoshuai1** [salt-ui/saltui#286]
> 请按照以下模板填写，不按照标准模板填写的 issue 将降低处理优先级。

## 这是一个BUG

- [x] 错误报告
     在用Tab的时候,下面如果做了滚动条,在安卓机型上面向上拖动无反应
- [x] 功能需求
    能够在多个tabItem下面做滚动条
## SaltUI 版本
  3.8.23

## 复现步骤

* https://codepen.io/zhangshaoshuai1/pen/MPJpNP

**Comment by eternalsky** [comment]
最新的3.x版本已经修复了这个问题，请先尝试升级解决。
