### ISSUE TITLE
InfiniteScroll安卓可以滚动，ios 无法滚动

### ISSUE THREAD

**Issue by krabs-xie** [salt-ui/saltui#290]
> 请按照以下模板填写，不按照标准模板填写的 issue 将降低处理优先级。

## 这是一个

- [x] InfiniteScroll安卓可以滚动，ios 无法滚动
- [ ] 功能需求

## 复现步骤

         <InfiniteScroll loading={this.state.loading} onLoad={this.onLoad.bind(this)} >
                    <div className="container">
                        <div className="inner">
                            <CourseList
                                currentCourse={this.state.currentCourse}
                                list={this.state.list}
                            />
                        </div>
                    </div>
                </InfiniteScroll>

**Comment by eternalsky** [comment]
请按照模板要求提 issue
