### ISSUE TITLE
滑动列表ScrollList滑到底部并快速下拉刷新会卡住

### ISSUE THREAD

**Issue by getEZ** [salt-ui/saltui#292]
> 请按照以下模板填写，不按照标准模板填写的 issue 将降低处理优先级。

## 这是一个

- [x] 错误报告
ScrollList中的列表分页数据不足一页时，上拉到列表底部并快速下拉刷新会卡住

## SaltUI 版本
*  4.1.15

## 浏览器、操作系统等环境信息
*  钉钉微应用

## 复现步骤

*  列表数据不足一页（数据少些能让页面上下滚动就可以了）
* 上拉到列表底部
*  快速下拉刷新列表
*  列表顶部的刷新效果会卡住不能刷新

**Comment by eternalsky** [comment]
请提供demo

**Comment by getEZ** [comment]
ScrollList需要动态数据，上拉并快速下拉刷新有问题
