### ISSUE TITLE
Table组件翻页事件没有返回页码

### ISSUE THREAD

**Issue by Zyyao11** [salt-ui/saltui#296]
> 请按照以下模板填写，不按照标准模板填写的 issue 将降低处理优先级。

## 这是一个

- [x] 错误报告
- [ ] 功能需求

## SaltUI 版本
4.1.2
## 浏览器、操作系统等环境信息
Chrome版本 70.0.3538.77（64 位）  mac10.13.6

## 复现步骤

* https://salt-ui.github.io/components/table
组件上 onPagerChange事件 （在翻页时触发，参数为要跳转的页数），没有这个参数，点击下一页或者上一页后，this.state.tableData.currentPage没有改变

**Comment by eternalsky** [comment]
issue 里贴的是官网的链接，官网链接经验证是可以返回对应页数的，this.state.tableData.currentPage 是什么不清楚。
