### ISSUE TITLE
tabbar控件onchange事件无法输出子按钮的值

### ISSUE THREAD

**Issue by YongBF** [salt-ui/saltui#297]
> 请按照以下模板填写，不按照标准模板填写的 issue 将降低处理优先级。

## 这是一个关于tabbar控件onchange事件的报错

- [x] 错误报告
- [ ] 功能需求
在saltui官网上选中中间按钮的子按钮时控制台会打印出‘2-0’形式的字符串（父级按钮的索引加上自身索引）,拷贝到本地进行测试时控制台会打印出undefined。

## SaltUI 版本
3.1.17

## 浏览器、操作系统等环境信息
win10操作系统， chrome浏览器。

## 复现步骤
demo拷贝至本地测试。

* 你可以在这里提交你的 [CodePen 链接](https://codepen.io/eternalsky/pen/WpzYrv) 以及描述复现的步骤

**Comment by eternalsky** [comment]
3.1.17 是很陈旧的版本，请先升级至最新版本。
