### ISSUE TITLE
iphone xs适配问题底部tabbar

### ISSUE THREAD

**Issue by z810276431** [salt-ui/saltui#299]
## 这是一个bug

- [x] 错误报告
- [ ] 功能需求

## 复现步骤

* 在iphone xs上看底部的tabbar
![1542265223 1](https://user-images.githubusercontent.com/16434735/48535717-2f182100-e8e7-11e8-9182-1743f611b350.jpg)

**Comment by eternalsky** [comment]
这个其实是 iphoneX 通用适配方案就可以做的，网上文章很多，随便找了一篇：https://aotu.io/notes/2017/11/27/iphonex/index.html

**Comment by z810276431** [comment]
谢谢，我去看一下
