### ISSUE TITLE
Popup无法改变导航栏标题

### ISSUE THREAD

**Issue by liuwf0314** [salt-ui/saltui#301]
> 请按照以下模板填写，不按照标准模板填写的 issue 将降低处理优先级。

## 这是一个

- [x] 错误报告
- [ ] 功能需求

## 复现步骤

* 你可以在这里提交你的 [CodePen 链接](https://codepen.io/eternalsky/pen/WpzYrv) 以及描述复现的步骤

**Comment by eternalsky** [comment]
Popup 只是弹出一个浮层，并不会去跳转页面，所以也不会改变导航栏标题，如果有改标题的需求，可以自己去调用 nativeAPI
