### ISSUE TITLE
页面下拉刷新时，连续下划两次，加载中就会卡住

### ISSUE THREAD

**Issue by liuwf0314** [salt-ui/saltui#311]
## 浏览器、操作系统等环境信息
安卓

## 复现步骤 

页面下拉刷新时，连续下划两次，加载中就会**卡住**

* [链接](https://salt-ui.github.io/components/scroll-list)

**Comment by eternalsky** [comment]
试下 4.x 的版本

**Comment by liuwf0314** [comment]
向上拉后快速向下拉，会出现这2个卡顿页面
![screenshot_20181128-145359](https://user-images.githubusercontent.com/30258444/49137520-a1e1bd00-f327-11e8-81a1-e8421df01a73.jpg)
![screenshot_20181128-145829](https://user-images.githubusercontent.com/30258444/49137521-a1e1bd00-f327-11e8-8a34-cd5ed27ff98a.jpg)
