### ISSUE TITLE
设置导航栏标题，对CalendarField组件的导航栏标题不起作用

### ISSUE THREAD

**Issue by liuwf0314** [salt-ui/saltui#312]
## 浏览器、操作系统等环境信息
安卓

## 复现步骤

*  直接使用CalendarField组件,标题设置不起作用[复现示例1](https://codepen.io/liuwf0314/pen/qQMeww) 
*  在popup中使用CalendarField组件，打开组件页面标题设置不起作用[复现示例2](https://codepen.io/liuwf0314/pen/vQVBBO)

**Comment by eternalsky** [comment]
没太看懂意思，CalendarField组件的导航栏标题指的是什么？

**Comment by liuwf0314** [comment]
手机的导航栏标题

**Comment by eternalsky** [comment]
设置手机的导航栏标题和 CalendarField 是完全不相关的两件事，CalendarField 只是在当前页面覆盖一个浮层，并不会对导航栏有任何影响。

**Comment by liuwf0314** [comment]
![-1](https://user-images.githubusercontent.com/30258444/49443068-59823d80-f806-11e8-95a4-20d6774a3107.jpg)

这是我提交的demo的效果，事实是确实手机的导航栏标题会恢复成设置之前的标题

**Comment by liuwf0314** [comment]
![-1](https://user-images.githubusercontent.com/30258444/49443872-820b3700-f808-11e8-8ffe-35fe64df9304.jpg)
结果显示是对导航栏有影响

**Comment by eternalsky** [comment]
组件有一个向 history 压状态的操作，用于拦截返回事件，可能这个导致了 浏览器 认为现在是一个全新的页面而后面单独设置的 title 失效，建议在 calendar 面板打开的时候，重新设置一下 title。
