### ISSUE TITLE
SearchBar 点击取消 不触发 onSearch & onChange

### ISSUE THREAD

**Issue by tommytroylin** [salt-ui/saltui#329]
## 这是一个

- [x] 错误报告

## SaltUI 版本
4.3.0

## 浏览器、操作系统等环境信息
chrome 70
iOS 12

## 复现步骤

* [CodePen 链接](https://codepen.io/tommytroylin/pen/EGZXOg?editors=1111)
* 键入任意字符。
* 点击 取消

**Comment by eternalsky** [comment]
你的 codePen demo 里我试了一下是可以触发 onChange 的。

**Comment by tommytroylin** [comment]
![1](https://user-images.githubusercontent.com/3364271/50285200-6fdef900-0496-11e9-8b02-1dbf529880ee.gif)

**Comment by eternalsky** [comment]
哦，你是说点击取消是吧，我刚才是试了点击 x

**Comment by tommytroylin** [comment]
对是的。
取消这个操作目前没有触发任何回调。
同时又把这个input清空了。

**Comment by eternalsky** [comment]
恩，这里 fix 一下。
