### ISSUE TITLE
Slot 等一些组件未对 iPhone X 进行适配

### ISSUE THREAD

**Issue by tommytroylin** [salt-ui/saltui#348]
请统一 review 下，确认需要适配的组件。

## 这是一个

- [x] 错误报告

## SaltUI 版本
4.x

## 浏览器、操作系统等环境信息
iOS 12
iPhone Xs Max

## 截图
![image](https://user-images.githubusercontent.com/3364271/53327898-c8fa5b80-3923-11e9-96aa-2007386ca2b1.png)

**Comment by veryStarters** [comment]
fixed @4.6.X
