### ISSUE TITLE
Table表格组件，无数据时，表头没有渲染

### ISSUE THREAD

**Issue by edc-hui** [salt-ui/saltui#352]
> 请按照以下模板填写，不按照标准模板填写的 issue 将降低处理优先级。

## 这是一个
- [x] 错误报告

## SaltUI 版本
4.4.18

## 浏览器、操作系统等环境信息
安卓 8.0 和 IOS 11.4.1

## 复现步骤
当表格组件的columns配置5列，并且表格无数据的时候，表格的表头渲染不出来。
saltUI官网文档上，表格组件无数据的示例中，即可看到此bug。
地址：https://salt-ui.github.io/components/table

**Comment by veryStarters** [comment]
fixed at saltui@4.4.19
