### ISSUE TITLE
PickerField 或 DateField 在 URL 上拼接的 query 不正确

### ISSUE THREAD

**Issue by zhangbenber** [salt-ui/saltui#356]
> 请按照以下模板填写，不按照标准模板填写的 issue 将降低处理优先级。

## 这是一个

- [x] 错误报告

## SaltUI 版本

4.4.21

## 浏览器、操作系统等环境信息

All

## 复现步骤

打开一个带 query 和 hash 的 URL，如：http://localhost/?test#test
点击任意 PickerField 或 DateField，URL 上拼接的 PICKER query 不正确

[https://github.com/salt-ui/saltui/blob/master/src/Picker/utils.js#L47](https://github.com/salt-ui/saltui/blob/master/src/Picker/utils.js#L47)

**Comment by eternalsky** [comment]
要多考虑有 hash 的情况，目前的函数里没有考虑 hash 已存在下的拼接方式
