### ISSUE TITLE
saltui从3.6.4升级到4.4.21，Toast.show不执行回调

### ISSUE THREAD

**Issue by feitiana03120** [salt-ui/saltui#360]
> 请按照以下模板填写，不按照标准模板填写的 issue 将降低处理优先级。

## 这是一个

- [x] 错误报告

## 浏览器、操作系统等环境信息
IOS

## 复现步骤

Toast.show回调函数不执行，本来用的saltui3.6.4版本，升级到4.4.21就出问题了

**Comment by veryStarters** [comment]
你说的不执行的回调函数是指哪个? @feitiana03120

**Comment by feitiana03120** [comment]
> 你说的不执行的回调函数是指哪个? @feitiana03120

onDidHide，另外还有一个问题，ScrollList下拉刷新后，加载图标不消失

**Comment by feitiana03120** [comment]
> 你说的不执行的回调函数是指哪个? @feitiana03120

为了使用EmployeeField所以才升级的，升级后遇到这两个问题。不升级EmployeeField没办法正常使用

**Comment by feitiana03120** [comment]
ScrollList下拉刷新的问题

![image](https://user-images.githubusercontent.com/14845860/55716101-b8f89000-5a28-11e9-954d-5a1cfe30e228.png)
