### ISSUE TITLE
升级saltUI之后，TextField组件的placeholder消失了

### ISSUE THREAD

**Issue by edc-hui** [salt-ui/saltui#366]
> 请按照以下模板填写，不按照标准模板填写的 issue 将降低处理优先级。

## 这是一个
- [x] 错误报告
## SaltUI 版本
4.6.1
## 浏览器、操作系统等环境信息
iOS12  和 安卓8.0

## 复现步骤

将saltUI版本升级至4.6.1之后，表单组件TextField的placeholder消失了。

复现步骤地址：https://codepen.io/edc-hui/pen/bJGepm?editors=0011

* 你可以在这里提交你的 [CodePen 链接](https://codepen.io/eternalsky/pen/WpzYrv) 以及描述复现的步骤

**Comment by veryStarters** [comment]
value确定不是最近改成null的吗？如果是空值，请使用''代替null
