### ISSUE TITLE
Filter组件使用报错

### ISSUE THREAD

**Issue by IIIThSoul** [salt-ui/saltui#370]
## 这是一个

- [x] 错误报告
- [ ] 功能需求

## SaltUI 版本 

4.6.5

## 浏览器、操作系统等环境信息

浏览器 Chrome  70.0.3538.110

操作系统 Win10

## 复现步骤

我按照样例：

![image](https://user-images.githubusercontent.com/10285557/57589817-90990f80-7559-11e9-884e-594d6ac70c25.png)

然后会报错显示 React 不存在

![image](https://user-images.githubusercontent.com/10285557/57589793-647d8e80-7559-11e9-8f76-1ff61504df71.png)

插件引入是这样的：

![image](https://user-images.githubusercontent.com/10285557/57589829-a6a6d000-7559-11e9-8347-6589a3196997.png)

**Comment by veryStarters** [comment]
fixed  saltui@4.6.9
