### ISSUE TITLE
嵌套使用带有showScroll属性的Tab控件时发生问题

### ISSUE THREAD

**Issue by LiangZugeng** [salt-ui/saltui#4]
我在一个页面嵌套使用了带有showScroll属性的控件，控件由代码生成，基本的结构为：
Tab
|-Tab.Item
　|-Tab
　　|-Tab.Item
　　|-Tab.Item
|-Tab.Item
　|-Tab
　　|-Tab.Item
　　|-Tab.Item

如果没有showScroll属性，在切换parentTab的Item时，此Tab.Item下的Tab显示正常（由于没有使用showScroll，tab.item只显示了第一个字符，这不是问题）。但把parentTab和childTab都加上showScroll属性时，只有第一个parent Tab.Item下的Tab显示正常，其他parent Tab.Item下的Tab都只显示第一个Tab.Item。参见附图。

**Repro代码地址：https://github.com/LiangZugeng/saltUITabIssue3Repro**

附图1：没有使用showScroll属性，第一个parent Tab.Item为激活状态：
![image](https://cloud.githubusercontent.com/assets/20870130/24136183/84ea8738-0e48-11e7-9b29-0c502b44b03f.png)

附图2：没有使用showScroll属性，第3个parent Tab.Item为激活状态：
![image](https://cloud.githubusercontent.com/assets/20870130/24136412/a5673834-0e49-11e7-9892-335e5238a8f6.png)

附图3：使用showScroll属性，第一个parent Tab.Item为激活状态：
![image](https://cloud.githubusercontent.com/assets/20870130/24136159/6ada5fa8-0e48-11e7-885f-a8d212d10351.png)

附图4：使用showScroll属性，第2个parent Tab.Item为激活状态：
![image](https://cloud.githubusercontent.com/assets/20870130/24136170/74be36de-0e48-11e7-8440-ab9aeae8cfa9.png)

**Comment by 2999** [comment]
感谢如此详细和认真的issue，已收到反馈。

另外，这样的交互方式，是否可以优化？如果一定要实现两层tab，不建议使用嵌套的方式。

**Comment by LiangZugeng** [comment]
我正在改结构，看是否能并行使用而不是嵌套，也麻烦你看看为什么嵌套会有问题。谢谢

**Comment by 2999** [comment]
好的，谢谢

**Comment by LiangZugeng** [comment]
我已经改结构了，不用嵌套，用并行的两个Tab，第一个Tab的Item里面没有任何内容。这样就没有显示的问题了。目前发现的另一个问题已经提交到Issue 5中。

**Comment by eternalsky** [comment]
outdated，reopen it if needed.
