### ISSUE TITLE
没引用salt-icon但在打包文件中出现该组件并占了1.3M

### ISSUE THREAD

**Issue by LiangZugeng** [salt-ui/saltui#404]
> 请按照以下模板填写，不按照标准模板填写的 issue 将降低处理优先级。

## 这是一个

- [x] 错误报告
- [ ] 功能需求

## SaltUI 版本
4.8.10

## 浏览器、操作系统等环境信息
Microsoft Edge 83.0.478.44 + Windows 10 Professional

## 现象
我们使用saltui但没有显式安装salt-icon（package.json里面没有依赖），代码里也没有import salt-icon，但在打包文件中salt-icon占了不少空间，请问如何去掉或者说减少空间使用。

![image](https://user-images.githubusercontent.com/20870130/83786614-7894b080-a6c5-11ea-9ae7-7df2db995e36.png)

**Comment by veryStarters** [comment]
saltui@4.8.33   fixed
