### ISSUE TITLE
目前如果要重写公司旧的钉钉h5微应用, 如果组件库还是选择saltui  构建工具有什么其他好的推荐么，nowa 好像都没怎么人用

### ISSUE THREAD

**Issue by BenLakes** [salt-ui/saltui#409]
> 请按照以下模板填写，不按照标准模板填写的 issue 将降低处理优先级。

## 这是一个

- [ ] 错误报告
- [x] 功能需求

## 复现步骤

* 你可以在这里提交你的 [CodePen 链接](https://codepen.io/eternalsky/pen/WpzYrv) 以及描述复现的步骤

**Comment by LiangZugeng** [comment]
Nowa以前我们也在用，因为当时遇到持续集成的某些问题，从18年某个时候就开始不用了，换为自己手写WebPack配置文件，版本是WebPack 4.0，那个项目使用WebPack一直延续到现在。后面新的项目使用的是create-react-app，跟着react的官方工具链走。

我个人认为可以先研究下WebPack，毕竟这些工具到最后都还是依赖WebPack，直接操作WebPack灵活性是最大的，只是比较繁琐，需要前期投入较多时间学习。等原理和概念都熟了以后，再转到某个脚手架，后面看脚手架的配置项都比较简单了。

另外我今天主要是来看看salt-ui最近是否活跃，公司最早的一个钉钉H5微应用还在使用salt-ui，现在在考虑要不要更换成其他UI控件库。salt-ui7月份有4个commits，8、9月没有，10月目前1个commit，如果不是功能特别稳定就是维护力度逐渐小了，看起来像后者，估计是投入的资源不足，以前这个好像是钉钉自己的团队在贡献，后来转给钉钉外部的团队了。如果要继续做，很多可以做的，比如全部组件转typescript，再比如加上单元测试，但随着钉钉对微应用开发方式的推荐方向改变（以前只有H5，现在推荐开发小程序），使用H5开发钉钉应用的会越来越少，估计以后salt-ui上面投入的资源也会越来越少。

前面这些是我个人的看法，如果 @eternalsky 或其他内部人士有其他看法，欢迎指正。
