### ISSUE TITLE
saltUI 是不是停止维护了，还有没有比这更好用的移动端UI库了。antd mobile感觉没有saltUI 好用

### ISSUE THREAD

**Issue by edc-hui** [salt-ui/saltui#421]
> 请按照以下模板填写，不按照标准模板填写的 issue 将降低处理优先级。

## 这是一个

- [x] 错误报告
- [ ] 功能需求

## 复现步骤

* 你可以在这里提交你的 [CodePen 链接](https://codepen.io/eternalsky/pen/WpzYrv) 以及描述复现的步骤

**Comment by edc-hui** [comment]
@eternalsky 你好，可以解答下这个疑问么？这个UI库曾经用过，现在想继续用下去，目前项目上全部使用ts开发了，所以想这个库能不能支持ts。saltUI 还是相当好用的

**Comment by eternalsky** [comment]
@edc-hui 非常遗憾的是目前 SaltUI 确实已经处于消极维护状态，不再迭代新的内容了，但目前仍然接受 pr 增加 feature 或修复 bug。
