### ISSUE TITLE
是否可以考虑升级一下react

### ISSUE THREAD

**Issue by zhouhailong** [salt-ui/saltui#43]
> 请按照以下模板填写

## 这是一个

- [ ] 错误报告
- [x] 功能需求

## 复现步骤

使用nowa创建的新工程，react是0.14.3版本，是否可以考虑升级一下react/react-dom/react-router等版本

**Comment by eternalsky** [comment]
https://github.com/salt-ui/saltui/issues/103 升级到 16 的需求。

**Comment by eternalsky** [comment]
已适配至 15.x，下一步向 16.x 适配。

**Comment by eternalsky** [comment]
4.x 已经适配 react16
