### ISSUE TITLE
关于SearchBar组件在完成搜索之后需自动退出搜索模式

### ISSUE THREAD

**Issue by bmnelson** [salt-ui/saltui#45]
## 这是一个

- [x] 功能需求

## SaltUI 版本
> 3.1.15
## 复现步骤

* 点击搜索框进入搜索模式
* 输入关键字按搜索或者完成进行搜索
* 搜索完成之后自动退出搜索模式

**Comment by eternalsky** [comment]
fix in https://github.com/salt-ui/saltui/commit/f6fff87e12b806041dff80e609cbec0cc82d56b2

**Comment by bmnelson** [comment]
Tested,problem solved.Thanks so much.
