### ISSUE TITLE
crumbs

### ISSUE THREAD

**Issue by singleclown** [salt-ui/saltui#47]
> 请按照以下模板填写

## 这是一个

- [] 错误报告
- [x] 功能需求

## SaltUI 版本
2.2.3
## 复现步骤
crumbs显示中的>需要提供一个配置项来修改内容例如改成：/
* 你可以在这里提交你的 CodePen 链接以及描述复现的步骤

**Comment by eternalsky** [comment]
fix in https://github.com/salt-ui/saltui/commit/cac8dfefb8870923b83645b5d155d772183d60d9
