### ISSUE TITLE
crumbs

### ISSUE THREAD

**Issue by singleclown** [salt-ui/saltui#48]
> 请按照以下模板填写

## 这是一个

- [] 错误报告
- [ x] 功能需求

## SaltUI 版本
2.2.3
## 复现步骤
crumbs里的>能否提供一个配置项可以修改例如改成“/”
* 你可以在这里提交你的 CodePen 链接以及描述复现的步骤

**Comment by eternalsky** [comment]
duplicate https://github.com/salt-ui/saltui/issues/47
