### ISSUE TITLE
在同一个页面使用多个带showScroll属性的Tab控件时第二个及以后的Tab控件的宽度计算有问题

### ISSUE THREAD

**Issue by LiangZugeng** [salt-ui/saltui#5]
同一个页面，并列使用多个带有showScroll属性的Tab控件，结构为：
`<Tab showScroll><Tab.Item/><Tab.Item/></Tab>
<Tab showScroll><Tab.Item/><Tab.Item/></Tab>`

当第二个Tab控件的Item元素的总宽度超过第一个Tab控件的Item元素总宽度太多时，第二个Tab控件的后面一些Item将会被换行，又由于Tab的高度固定，所以从界面上来看后面的这些换行的Item感觉就像是没被渲染或者丢失了。

![image](https://cloud.githubusercontent.com/assets/20870130/24192688/c48f765e-0f2a-11e7-8db5-9f186d3e0011.png)
附图：第二个Tab应该显示到30，但最后一个显示的元素为28

解决方案已经由@光弘 通过钉钉提供，在第二个和以后的Tab上加上key属性并赋不同的值。

请修复此bug。

**Comment by eternalsky** [comment]
outdated，reopen it if needed.
