### ISSUE TITLE
Collapse组件的上下箭头不能显示，显示的是乱码

### ISSUE THREAD

**Issue by panjiefeng** [salt-ui/saltui#53]
> 请按照以下模板填写

## Collapse组件的上下箭头不能显示，现实的是乱码

- [x] 错误报告

## 复现步骤
1. 将官网的代码copy，然后访问，箭头显示异常。
![image](https://user-images.githubusercontent.com/11753235/34194868-d78f75be-e595-11e7-9e2f-d2a0e752c973.png)
官网正常效果
![image](https://user-images.githubusercontent.com/11753235/34194893-ef3268f2-e595-11e7-8981-959a14e695fe.png)
本地访问效果
* 你可以在这里提交你的 CodePen 链接以及描述复现的步骤

**Comment by eternalsky** [comment]
请提交 codePen 复现demo，https://codepen.io/eternalsky/pen/WpzYrv

**Comment by panjiefeng** [comment]
在codeopen网页上访问没有问题， https://codepen.io/panjunfen/pen/ZvOMoe 
但是export出zip在本地访问有问题，Chrome和UC浏览器都是一样
![image](https://user-images.githubusercontent.com/11753235/34243457-cf7f3db6-e65b-11e7-8b82-133d866ee49c.png)

**Comment by eternalsky** [comment]
你本地有没有联网？要请求外部字体的

**Comment by panjiefeng** [comment]
本地联网了的，那外部字体能不能下载到本地导入程序？是哪个字体呢？

**Comment by panjiefeng** [comment]
知道了谢谢提醒。在dd.min.css中定义了一个iconfont：
`@font-face {
  font-family: 'iconfont';  /* project id 353381 */
  src: url('//at.alicdn.com/t/font_2rlrsccxhkf0f6r.woff') format('woff');
}`
本地访问不了那个链接，把字体下载下来，换成本地字体就可以了
