### ISSUE TITLE
searchbar组件 隐藏键盘的动画，均会出现上一个页面的样式

### ISSUE THREAD

**Issue by lf75152798** [salt-ui/saltui#57]
## 这是一个

功能需求

## SaltUI 版本

 //g.alicdn.com/platform/tingle-ui/2.2.3/salt-ui.min.js

## 浏览器、操作系统等环境信息
安卓手机会出现，有的时候快，有的手机慢

## 复现步骤
安卓手机
searchbar 搜索结果的列表，在输入框输入内容时，键盘会弹出。当收起键盘的时候，可以看到  class  t-search-bar-list     的 css 属性   position: fixed;    当键盘收起的过程中，可以看到    t-search-bar-list 覆盖元素下的 那部分内容

**Comment by eternalsky** [comment]
建议按照项目 readme 的方法升级至 3.x  版本，附带 升级指南，https://github.com/salt-ui/saltui/issues/21
