### ISSUE TITLE
Dialog.alert 使用报错

### ISSUE THREAD

**Issue by smilexlong** [salt-ui/saltui#58]
> 请按照以下模板填写

## 这是一个

- [x] 错误报告
- [ ] 功能需求

## SaltUI 版本
3.1.31
react 0.14.9

## 浏览器、操作系统等环境信息
chrome,win7  使用creact-react-app  创建的项目

## 复现步骤
页面中引入 import Dialog from 'saltui/lib/Dialog'

在点击事件中
addNurse() {
 Dialog.alert({
            title: '测试',
            content: '我是 Dialog.alert 的调用',
            onConfirm() {
                console.log('alert confirm');
            },
        });
}

` <button key="aler" onClick={this.addNurse.bind(this)}>add person</button>`

报以下错误：
index.js:2177 Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `Dialog`.

**Comment by eternalsky** [comment]
请提供 codePen demo https://codepen.io/eternalsky/pen/WpzYrv，目前按照你的代码，跟站点是一致的，没有发现该问题。

**Comment by smilexlong** [comment]
在codepan上没报错，在我用creat-react-app创建的上面报错 ，这是我临时建的一个demo：https://github.com/smilexlong/saltuiDemo，就是报这个错  React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of Dialog.

**Comment by eternalsky** [comment]
检查你的 React 使用版本，目前 saltui 支持到 0.14.x

**Comment by smilexlong** [comment]
我使用的就是 react 就是0.14.9，react-dom 也是0.14.9的  我上面提供的demo 就是这个版本的，其他的组件使用没什么问题，目前就这个Diago报错

**Comment by eternalsky** [comment]
你的脚手架目前使用的是 webpack 3，webpack 3 需要配置 resolve.mainFields 为 main，来保证不引入 es6 模块，建议你做一下修改，如果您不会修改，建议直接使用我们 ReadME 中提供的脚手架开发工具，进行开发，他的配置是比较明显的，而且用这个工具启动调试，不需要再进行上面的配置。

**Comment by smilexlong** [comment]
![image](https://user-images.githubusercontent.com/19772709/34346316-559afc22-ea31-11e7-91a9-62524f1cab05.png)
 这样配置了还不行

**Comment by eternalsky** [comment]
mainFields 要配置成 main。。请看我上个回复里的链接。。

**Comment by smilexlong** [comment]
mainFields: ['main'], 这样配置就会报错，

![qq 20171226133649](https://user-images.githubusercontent.com/19772709/34347912-dea79b50-ea41-11e7-83d9-bec755cc4275.png) 官方creat-react-app 脚手架引用的资源比较多，目前看不能只单独设置成main，不知道saltui什么时候能升级一下，去掉这些限制

**Comment by eternalsky** [comment]
至少，去掉 module

**Comment by smilexlong** [comment]
mainFields:['browser','main']，这样可以正常使用了，不知道去掉module 不会回有其他影响

**Comment by eternalsky** [comment]
你可以先了解一下 module 是干什么的，就知道会不会有影响了，一般来说，如果你没有用到 treeShaking，就不会有什么影响。

**Comment by smilexlong** [comment]
好的，谢谢，我去了解一下
