### ISSUE TITLE
带有showScroll属性的Tab控件在Tab.Item变化时宽度没有调整

### ISSUE THREAD

**Issue by LiangZugeng** [salt-ui/saltui#6]
这里又提一个Tab控件的问题。带有showScroll属性的Tab控件，在同一页面由于其他事件触发了Tab.Item个数变化后，宽度没有调整。

例子：http://codepen.io/LiangZugeng/pen/bqjMrV

第一次渲染只有一个Tab.Item，点击按钮后重新生成tabs数组，这次渲染有10个Tab.Item，可以看出再次Render以后Tab可见的Item还是一个（title改变了），但剩下的9个被折行了，看不见。

**Comment by eternalsky** [comment]
outdated，reopen it if needed.
