### ISSUE TITLE
salt-ui.css对Refreshcontrol的下拉刷新有影响

### ISSUE THREAD

**Issue by zhouhailong** [salt-ui/saltui#61]
> 请按照以下模板填写

## 这是一个

- [x] 错误报告
- [ ] 功能需求

## 浏览器、操作系统等环境信息
salt-ui版本3.1.29

## 复现步骤

Refreshcontrol的例子，加上salt-ui的css后下拉刷新失效，
// @import '~saltui/build/salt-ui.css';如果注释掉css的引入，虽然样式有问题，但是功能正常了

* 追加：@import '~saltui/build/net-blue.css';使用这个主题的样式，下拉刷新功能正常 *

**Comment by eternalsky** [comment]
感觉不太可能是这个原因，两个 css，除了一些颜色上取了不同的数值，其他一模一样。

**Comment by eternalsky** [comment]
没有具体复现 demo，暂时关闭，请提交复现 Demo 后再重新 open
