### ISSUE TITLE
locale 的配置与 uxcore 不同

### ISSUE THREAD

**Issue by fengsx** [salt-ui/saltui#64]
> 请按照以下模板填写

## 这是一个

- [ ] 错误报告
- [x] 功能需求

## SaltUI 版本
3.3.2
## 复现步骤
uxcore 的国际化语言标记是 zh-cn, en-us
但是 salt-ui 是 zh_CN，en_US
两者能否保持统一

**Comment by eternalsky** [comment]
有计划后面统一成  zh-cn，这种，但兼容 zh_CN 这种，目前还没开工。

**Comment by eternalsky** [comment]
Done，所有组件 locale 统一至于 uxcore 相同的 zh-cn 形式，原有支持 zh_CN 的组件兼容这种数据格式。
