### ISSUE TITLE
单选框RadioField组件Bug

### ISSUE THREAD

**Issue by magicsay** [salt-ui/saltui#65]
> 请按照以下模板填写

## 这是一个 => 样式BUG

- [ ] 错误报告
页面无报错。
有数据回调，样式却没有变化。
单选的所有项目固定被全部色选。

- [ ] 功能需求
根据用户操作勾选被操作项目。

## 浏览器、操作系统等环境信息
 => IOS、chrome 版本 63.0.3239.84、win7 x64

## 复现步骤
 => 根据Demo引用到自己的项目中。

* 你可以在这里提交你的 CodePen 链接以及描述复现的步骤

**Comment by eternalsky** [comment]
duplicate：https://github.com/salt-ui/saltui/issues/63
