### ISSUE TITLE
SelectField 首次弹出点击确定，无法选中第一个选项

### ISSUE THREAD

**Issue by fengsx** [salt-ui/saltui#69]
> 请按照以下模板填写

## 这是一个

- [x] 错误报告
- [ ] 功能需求

## SaltUI 版本
3.3.2
## 浏览器、操作系统等环境信息
React 15.4.1

## 复现步骤
1、先点击输入框，弹出 slot。slot 这时的选中状态会在第一个选项上。
2、直接点击确定，第一个值并没有被选中
![image](https://user-images.githubusercontent.com/7709602/34518758-dd12c852-f0bb-11e7-9ca5-ca6428567758.png)

* 你可以在这里提交你的 CodePen 链接以及描述复现的步骤

**Comment by eternalsky** [comment]
fix in https://github.com/salt-ui/saltui/commit/c6f23a2442631bae8ff31b329a85d51446a7c9b8
