### ISSUE TITLE
CheckboxFiled readonly 和 disable 样式叠加的问题

### ISSUE THREAD

**Issue by fengsx** [salt-ui/saltui#72]
> 请按照以下模板填写

## 这是一个

- [x] 错误报告
- [ ] 功能需求

## SaltUI 版本
3.3.6
## 复现步骤
CheckboxFiled 设置 readOnly 为 true， 同时 CheckboxFiled 的 data 中的选项设置 disable 为 true。样式如下：

![image](https://user-images.githubusercontent.com/7709602/34548775-ddc3822c-f13e-11e7-92fd-79ef03f5eda1.png)

* 你可以在这里提交你的 CodePen 链接以及描述复现的步骤

**Comment by eternalsky** [comment]
目前问题不明确，先关闭
