### ISSUE TITLE
RadioField 的未选中样式问题

### ISSUE THREAD

**Issue by fengsx** [salt-ui/saltui#73]
> 请按照以下模板填写

## 这是一个

- [ ] 错误报告
- [x] 功能需求

## 浏览器、操作系统等环境信息
3.3.6

## 复现步骤
如下图，RadioField 的 data 在没有配置 checked 项的时候，展示如下：
![image](https://user-images.githubusercontent.com/7709602/34548895-8fc1e82e-f13f-11e7-95e4-68167e8a136b.png)
用户很难觉察到这里是可以选择的项

* 你可以在这里提交你的 CodePen 链接以及描述复现的步骤

**Comment by eternalsky** [comment]
这种直接渲染在页面上的，需要标题去引导。

**Comment by eternalsky** [comment]
目前问题不明确，先关闭
