### ISSUE TITLE
TabBarItemBadge need a key 

### ISSUE THREAD

**Issue by fengsx** [salt-ui/saltui#74]
> 请按照以下模板填写

## 这是一个

- [x] 错误报告
- [ ] 功能需求

## SaltUI 版本
3.3.6
## 复现步骤
![image](https://user-images.githubusercontent.com/7709602/34553490-b50921c4-f162-11e7-8c8b-d4f3f3f01307.png)

* 你可以在这里提交你的 CodePen 链接以及描述复现的步骤

**Comment by eternalsky** [comment]
排查了一下，这个问题在最新版中应该已经没有了
