### ISSUE TITLE
icon 文档说明错误

### ISSUE THREAD

**Issue by fengsx** [salt-ui/saltui#76]
> 请按照以下模板填写

## 这是一个

- [x] 错误报告
- [ ] 功能需求

## SaltUI 版本
3.3.6
## 复现步骤
`angel-right` 等跟 `angle` 有关的单词，拼错成了 `angel`
![image](https://user-images.githubusercontent.com/7709602/34556536-a777a88c-f171-11e7-8693-0b6aacea6d3f.png)

* 你可以在这里提交你的 CodePen 链接以及描述复现的步骤

**Comment by eternalsky** [comment]
能具体说明一下是哪里拼成 `angel` 了吗？排查了一下之后，都是 `angle`
