### ISSUE TITLE
tabbar不支持base64编码后的图片地址

### ISSUE THREAD

**Issue by Jirapo** [salt-ui/saltui#8]
tabbar组件对图标替换中，包含了图片地址url的判断，导致如果引入的图片是base64编码后的图片，那么就无法显示替换后的图片了。

**Comment by tommytroylin** [comment]
![image](https://cloud.githubusercontent.com/assets/3364271/25083511/156990c8-238a-11e7-801d-d8e72e36048d.png)

tingle-tab-bar/src/TabBarItem.js Line 16
