### ISSUE TITLE
scrollView

### ISSUE THREAD

**Issue by 185172970** [salt-ui/saltui#81]
## 这是一个

- [x] 错误报告

## 复现几率低

*在 ScrollView.jsx doScroll（）{}函数里面
const { scrollTop } = this.scrollView;
这段代码会报错
ref={(ref) => { this.scrollView = ref; }}
在dom没有完全加载完成的时候调用ref，

**Comment by eternalsky** [comment]
需要一个复现 Demo：https://codepen.io/eternalsky/pen/WpzYrv

**Comment by 185172970** [comment]
组件自己scrollList内部调用scrollView，我怎么用代码复现啊

**Comment by 185172970** [comment]
http://carport.alibaba.net/carport/mobile/index.htm#/people?_k=ppdyrg 在这个页面连续下拉翻页，然后再上拉刷新偶尔会出现报错

**Comment by eternalsky** [comment]
@185172970 注意不要把 内部链接发出来。

**Comment by eternalsky** [comment]
@185172970 那你可以做一个可以复现问题的 scrollList 的 复现 demo

**Comment by 185172970** [comment]
<div style={{ height: window.innerHeight }} className='border-top' >
      <ScrollList
        url={'/carport/portgrabrecord/getPortShareRecordPageResult.json'}
        noDataImage={'https://img.alicdn.com/tfs/TB1V3c2cOqAXuNjy1XdXXaYcVXa-300-300.png'}
        noDataTip={'这里空空如也'}
        pageSize={10}
        beforeFetch={(data) => {
          data.orderByType = 'asc'
          return data
        }}
        processData={(data) => data}>
        <Item />
      </ScrollList>
    </div>就是这种用法，而且还有另一个bug，为空的时候背景图，没有宽高，所以背景图也无法出现

**Comment by 185172970** [comment]
<div style={{ height: window.innerHeight }} className='border-top' >
      <ScrollList
        url={'/carport/portgrabrecord/getPortShareRecordPageResult.json'}
        noDataImage={'https://img.alicdn.com/tfs/TB1V3c2cOqAXuNjy1XdXXaYcVXa-300-300.png'}
        noDataTip={'这里空空如也'}
        pageSize={10}
        beforeFetch={(data) => {
          data.orderByType = 'asc'
          return data
        }}
        processData={(data) => data}>
        <Item />
      </ScrollList>
    </div>

**Comment by eternalsky** [comment]
没有复现 demo 的话，修复的优先级会降低，感谢理解。

**Comment by 185172970** [comment]
scrollList就一个url，复现也没什么意义啊，而且我这里也不容易复现，要不周一我搬电脑去找你吧

**Comment by zkl5999** [comment]
IOS 为什么一开始不显示
