### ISSUE TITLE
关于SearchBar组件在回车搜索后触发两次onSearch函数的问题

### ISSUE THREAD

**Issue by bmnelson** [salt-ui/saltui#84]
## 这是一个

- [x] 错误报告
- [ ] 功能需求

## 复现步骤

* 点击SearchBar中输入框后进入搜索模式
* 输入任意关键词后输入回车搜索
* 触发一次onSearch函数
* 几秒后再一次自动将关键词复位成空值后再触发了一次onSearch函数

**Comment by bmnelson** [comment]
anybody here to help?

**Comment by eternalsky** [comment]
有个点可以看下：

1. 看自己需不需要 instantSearch
2. 几天会上线一个优化，enter 的时候取消 debounce 里的 search
