### ISSUE TITLE
SaltUI组件中Slide轮播里面的onSlideClick事件存在点击一次，触发两次的bug

### ISSUE THREAD

**Issue by Iris-2017** [salt-ui/saltui#9]
![default](https://cloud.githubusercontent.com/assets/25760005/26289209/964a0dce-3ed0-11e7-9059-2247cbb6ca09.png)第一次显示当前项，第二次默认跳转第0项
请修复此bug

**Comment by eternalsky** [comment]
outdated，reopen it if needed.
